-- DDL migration for THE.HBS_EDIT_ERR_MESSAGE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE HBS_EDIT_ERR_MESSAGE_CODE (
    HBS_EDIT_ERR_MESSAGE_CODE VARCHAR2(6) NOT NULL,
    HBS_EDIT_ERR_CATEGORY_CODE VARCHAR2(3) NOT NULL,
    HBS_EDIT_ERR_RESPONSIBLTY_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C007793 CHECK (HBS_EDIT_ERR_MESSAGE_CODE IS NOT NULL),
    CONSTRAINT SYS_C007794 CHECK (HBS_EDIT_ERR_CATEGORY_CODE IS NOT NULL),
    CONSTRAINT SYS_C007795 CHECK (HBS_EDIT_ERR_RESPONSIBLTY_CODE IS NOT NULL),
    CONSTRAINT SYS_C007796 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C007797 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C007798 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C007799 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE HBS_EDIT_ERR_MESSAGE_CODE ADD CONSTRAINT EEMC_PK PRIMARY KEY (HBS_EDIT_ERR_MESSAGE_CODE, HBS_EDIT_ERR_CATEGORY_CODE);

-- Indexes
CREATE INDEX EEMC_ECC_FK_I ON HBS_EDIT_ERR_MESSAGE_CODE (HBS_EDIT_ERR_CATEGORY_CODE);

-- Foreign Keys
