-- DDL migration for THE.WASTE_ACCUMULATED_CV_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE WASTE_ACCUMULATED_CV_CODE (
    WASTE_ACCUMULATED_CV_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0023371 CHECK (WASTE_ACCUMULATED_CV_CODE IS NOT NULL),
    CONSTRAINT SYS_C0023373 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0023375 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0023377 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0023379 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE WASTE_ACCUMULATED_CV_CODE ADD CONSTRAINT WACV_PK PRIMARY KEY (WASTE_ACCUMULATED_CV_CODE);

-- Indexes

-- No foreign keys found
