-- DDL migration for THE.INTERIOR_WMRF_GRADE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE INTERIOR_WMRF_GRADE_CODE (
    INTERIOR_WMRF_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0018746 CHECK (INTERIOR_WMRF_GRADE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0018748 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0018750 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0018753 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0018756 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE INTERIOR_WMRF_GRADE_CODE ADD CONSTRAINT IWGC_PK PRIMARY KEY (INTERIOR_WMRF_GRADE_CODE);

-- Indexes

-- No foreign keys found
