-- DDL migration for WASTE_AREA_RISK_RATING_CODE (DBeaver style)
CREATE TABLE WASTE_AREA_RISK_RATING_CODE (
    WASTE_AREA_RISK_RATING_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023763 CHECK (WASTE_AREA_RISK_RATING_CODE IS NOT NULL);
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023764 CHECK (DESCRIPTION IS NOT NULL);
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023765 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023766 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023767 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT WARRC_PK PRIMARY KEY (WASTE_AREA_RISK_RATING_CODE);

-- Unique Index

-- No foreign keys found
