-- DDL Migration for SAMPLE_LOG_TALLY (DBeaver style)
-- Table columns
CREATE TABLE SAMPLE_LOG_TALLY (
    DETAIL_DOCUMENT_NUMBER VARCHAR2(13) NOT NULL,
    VERSION NUMBER(2,0) NOT NULL,
    BATDOC_ID NUMBER(32,0),
    SCALE_EVENT_TYPE_CODE VARCHAR2(2) NOT NULL,
    SCL_RTN_VERSION_STATE_CODE VARCHAR2(3) NOT NULL,
    SCALE_DATE DATE NOT NULL,
    SCALE_SITE_ID_NMBR VARCHAR2(4),
    POPULATION_NUMBER VARCHAR2(4),
    STRATUM_NUMBER VARCHAR2(2),
    SAMPLING_YEAR NUMBER(5,0),
    TIMBER_MARK VARCHAR2(6),
    TIMBER_BRAND VARCHAR2(7),
    PRIMARY_QUANT_LIC_TYPE_CD VARCHAR2(1),
    PRIMARY_LICENSE_NUMBER VARCHAR2(4),
    SECONDARY_QUANT_LIC_TYPE_CD VARCHAR2(1),
    SECONDARY_LICENSE_NUMBER VARCHAR2(4),
    SIGNING_QUANT_LIC_TYPE_CD VARCHAR2(1),
    SIGNING_LICENSE_NUMBER VARCHAR2(4),
    SAMPLED_WEIGH_SLIP VARCHAR2(10),
    SAMPLE_WEIGHT NUMBER(6,0),
    RETURN_NUMBER NUMBER(4,0) NOT NULL,
    LOG_COUNT NUMBER(4,0) NOT NULL,
    NET_VOLUME NUMBER(7,3),
    VOLUME_CALC_METHOD_TYPE VARCHAR2(1),
    ORIG_CHK_SCL_QUANT_LIC_TYPE_CD VARCHAR2(1),
    ORIGINAL_DDN VARCHAR2(13),
    ORIGINAL_DDV NUMBER(2,0),
    ORIG_CHK_SCL_LICENSE_NUMBER VARCHAR2(4),
    ORIG_CHK_SCL_RETURN_NUMBER NUMBER(4,0),
    ORIG_REDTAG_SCALE_SITE_ID_NMBR VARCHAR2(4),
    ACTIVE_VERSION_IND VARCHAR2(1) NOT NULL,
    VALID_SIGNATURE_IND VARCHAR2(1) NOT NULL,
    CHECK_REPLACES_ORIGINAL_IND VARCHAR2(1),
    ORIGINAL_VERSION_IND VARCHAR2(1) NOT NULL,
    TRANSPORT_IDENTIFIER VARCHAR2(16),
    INCOMING_LDS_NUMBER VARCHAR2(10),
    LOAD_ARRIVAL_NUMBER VARCHAR2(10),
    SAMPLE_LOG_TALLY_COMMENT VARCHAR2(240),
    DTL_DOC_SEQ NUMBER(32,0) NOT NULL,
    INPUT_SCALE_SITE VARCHAR2(4),
    INPUT_ORIG_REDTAG_SCL_SITE VARCHAR2(4),
    INPUT_SOURCE VARCHAR2(7),
    INPUT_PRIMARY_SCALER_LIC VARCHAR2(4),
    INPUT_PSY VARCHAR2(8),
    INPUT_SECONDARY_SCALER_LIC VARCHAR2(4),
    INPUT_SIGNING_SCALER_LIC VARCHAR2(4),
    INPUT_ORIGINAL_DDN VARCHAR2(13),
    INPUT_ORIGINAL_DDV NUMBER(2,0),
    INPUT_ORIG_CHK_SCL_SCALER_LIC VARCHAR2(4),
    FIELD_SCALE_DECK_ID VARCHAR2(1),
    ENCRYPTED_SIGNATURE RAW(512),
    HBS_ENCR_KEY_ID NUMBER(2,0),
    INPUT_HBS_ENCR_KEY_ID NUMBER(2,0),
    HBS_RSA_PADDING_ID NUMBER(2,0),
    DECRYPTED_SIGNATURE VARCHAR2(128),
    HASH_TOTAL VARCHAR2(128),
    HBS_CRYPT_METHOD_ID NUMBER(2,0),
    SIGNING_DATE_TIME DATE,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30),
    UPDATE_TIMESTAMP DATE
);

-- Explicit CHECK constraints (NOT NULL and other conditions)
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017740 CHECK (DETAIL_DOCUMENT_NUMBER IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017741 CHECK (VERSION IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017742 CHECK (SCALE_EVENT_TYPE_CODE IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017744 CHECK (SCL_RTN_VERSION_STATE_CODE IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017746 CHECK (SCALE_DATE IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017748 CHECK (RETURN_NUMBER IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017750 CHECK (LOG_COUNT IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017751 CHECK (ACTIVE_VERSION_IND IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017752 CHECK (VALID_SIGNATURE_IND IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017753 CHECK (ORIGINAL_VERSION_IND IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017754 CHECK (DTL_DOC_SEQ IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017755 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0017756 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0039131 CHECK (ACTIVE_VERSION_IND IN ('Y', 'N'));
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0039132 CHECK (CHECK_REPLACES_ORIGINAL_IND IN ('Y', 'N'));
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0039133 CHECK (ORIGINAL_VERSION_IND IN ('Y', 'N'));
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SYS_C0039134 CHECK (VOLUME_CALC_METHOD_TYPE IN ('G', 'N'));
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT C$08_SAMPLE_TLY_LOG_COUNT CHECK (LOG_COUNT > 0);
-- Additional complex check constraints omitted for brevity

-- Primary Key
ALTER TABLE SAMPLE_LOG_TALLY ADD CONSTRAINT SAMPLE_LOG_TALLY_PK PRIMARY KEY (DETAIL_DOCUMENT_NUMBER, VERSION);

-- Indexes
CREATE INDEX SMPLOGTLY_STRATUM_FK_I ON SAMPLE_LOG_TALLY (POPULATION_NUMBER, STRATUM_NUMBER, SAMPLING_YEAR);
CREATE INDEX SMPLOGTLY_SRVERSTATE_FK_I ON SAMPLE_LOG_TALLY (SCL_RTN_VERSION_STATE_CODE);
CREATE INDEX SMPLOGTLY_SETC_FK_I ON SAMPLE_LOG_TALLY (SCALE_EVENT_TYPE_CODE);
CREATE INDEX SMPLOGTLY_MOF_TM_FK_I ON SAMPLE_LOG_TALLY (TIMBER_MARK);
CREATE INDEX SMPLOGTLY_MOF_SS_FK_I ON SAMPLE_LOG_TALLY (SCALE_SITE_ID_NMBR);
CREATE INDEX SMPLOGTLY_BATDOC_FK_I ON SAMPLE_LOG_TALLY (BATDOC_ID);
CREATE INDEX SMPLOGTLY_HRPS_FK_I ON SAMPLE_LOG_TALLY (HBS_RSA_PADDING_ID);
CREATE INDEX SMPLOGTLY_HCM_FK_I ON SAMPLE_LOG_TALLY (HBS_CRYPT_METHOD_ID);
CREATE INDEX SMPLOGTLY_HEK_FK1_I ON SAMPLE_LOG_TALLY (HBS_ENCR_KEY_ID);
-- Additional indexes omitted for brevity

-- Foreign Keys (commented for later use)
