-- DDL Migration for WASTE_ASSESSMENT_AREA_HISTORY (DBeaver style)
-- Table columns
CREATE TABLE WASTE_ASSESSMENT_AREA_HISTORY (
    WASTE_FIBRE_RECOVERY_ZONE_RATE VARCHAR2(1),
    OBLIGATION_ADJUSTMENT NUMBER(5,2),
    WASTE_CONDITION_TYPE_CODE VARCHAR2(3),
    WASTE_SITE_TYPE_CODE VARCHAR2(2),
    WASTE_HARVEST_STATUS_CODE VARCHAR2(4),
    WASTE_NET_AREA NUMBER(5,2) NOT NULL,
    MARK_AREA NUMBER(5,2),
    REMAINING_HARVEST_AREA NUMBER(5,2),
    YEAR_LOGGED_FROM NUMBER(4,0),
    YEAR_LOGGED_TO NUMBER(4,0),
    PRIMARY_LOGGING_COMPLETE_DATE DATE,
    ASSESS_STATUS_CHANGE_DATE DATE,
    BENCHMARK_VOLUME NUMBER(2,0),
    WASTE_SURVEYOR_LICENCE VARCHAR2(4),
    RETURN_NUMBER VARCHAR2(4),
    WASTE_ROADS_AREA NUMBER(4,2),
    SURVEY_DATE DATE,
    CRUISE_VOLUME NUMBER(4,0),
    WASTE_ASSESS_AREA_STS_CODE VARCHAR2(4) NOT NULL,
    PARENT_BLOCK_IND VARCHAR2(1) NOT NULL,
    CHILD_BLOCK_IND VARCHAR2(1) NOT NULL,
    MULTI_MARK_IND VARCHAR2(1) NOT NULL,
    WASTE_PARENT_BLOCK_TYPE_CODE VARCHAR2(2),
    DOCUMENT_CONTROL_NUMBER NUMBER(10,0),
    HBS_EDIT_ERR_MESSAGE_CODE VARCHAR2(6),
    HBS_EDIT_ERR_CATEGORY_CODE VARCHAR2(3),
    DRAFT_TIMBER_MARK VARCHAR2(10),
    DRAFT_CUTTING_PERMIT_ID VARCHAR2(3),
    DRAFT_CUT_BLOCK_ID VARCHAR2(10),
    CUTTING_PERMIT_ID VARCHAR2(3),
    CUT_BLOCK_ID VARCHAR2(10),
    WASTE_SURVEY_CHECK_CODE VARCHAR2(3),
    NUMBER_OF_PLOTS_CHECKED NUMBER(3,0),
    WASTE_AREA_RISK_RATING_CODE VARCHAR2(3),
    INVOICE_NOTATION VARCHAR2(80),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    WASTE_HISTORY_ID NUMBER(12,0) NOT NULL,
    PARENT_WAA_ID NUMBER(12,0),
    REPORTING_UNIT_ID NUMBER(12,0) NOT NULL,
    FOREST_FILE_ID VARCHAR2(10) NOT NULL,
    TIMBER_MARK VARCHAR2(6),
    CB_SKEY NUMBER(10,0),
    WASTE_MATURITY_TYPE_CODE VARCHAR2(8)
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020673 CHECK (WASTE_HISTORY_ID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020674 CHECK (REPORTING_UNIT_ID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020675 CHECK (FOREST_FILE_ID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020676 CHECK (WASTE_NET_AREA IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020677 CHECK (WASTE_ASSESS_AREA_STS_CODE IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020678 CHECK (PARENT_BLOCK_IND IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020679 CHECK (CHILD_BLOCK_IND IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020680 CHECK (MULTI_MARK_IND IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020681 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020682 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020683 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020684 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT SYS_C0020685 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT WAAH_PK PRIMARY KEY (WASTE_HISTORY_ID);

-- Indexes

-- Foreign Keys (commented for later use)
