-- DDL Migration for WASTE_PIECE_HISTORY (DBeaver style)
-- Table columns
CREATE TABLE WASTE_PIECE_HISTORY (
    WASTE_PIECE_ID NUMBER(12,0) NOT NULL,
    WASTE_HISTORY_ID NUMBER(12,0) NOT NULL,
    WASTE_PLOT_ID NUMBER(12,0),
    WASTE_STRATUM_ID NUMBER(12,0),
    WASTE_PIECE_NUMBER NUMBER(3,0) NOT NULL,
    WASTE_MATERIAL_KIND_CODE VARCHAR2(1) NOT NULL,
    WASTE_CLASS_CODE VARCHAR2(1) NOT NULL,
    SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    SCALE_PRODUCT_CODE VARCHAR2(2) NOT NULL,
    SCALE_SPECIES_CODE VARCHAR2(2) NOT NULL,
    LENGTH NUMBER(3,0),
    TOP_DIAMETER NUMBER(3,0),
    TOP_END_CODE VARCHAR2(1),
    BUTT_DIAMETER NUMBER(3,0),
    BUTT_END_CODE VARCHAR2(1),
    WASTE_BORDERLINE_CODE VARCHAR2(1),
    LENGTH_DEDUCTION NUMBER(4,1),
    TOP_DEDUCTION NUMBER(3,0),
    BUTT_DEDUCTION NUMBER(3,0),
    WASTE_DECAY_TYPE_CODE VARCHAR2(1),
    WASTE_COMMENT_CODE VARCHAR2(2),
    ESTIMATED_VOLUME NUMBER(8,3),
    ESTIMATED_PERCENT NUMBER(4,1),
    DENSITY_ESTIMATE NUMBER(8,3),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020621 CHECK (WASTE_PIECE_ID IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020623 CHECK (WASTE_HISTORY_ID IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020625 CHECK (WASTE_PIECE_NUMBER IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020626 CHECK (WASTE_MATERIAL_KIND_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020627 CHECK (WASTE_CLASS_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020628 CHECK (SCALE_GRADE_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020629 CHECK (SCALE_PRODUCT_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020630 CHECK (SCALE_SPECIES_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020631 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020632 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020633 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020634 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT SYS_C0020635 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT WPIEH_PK PRIMARY KEY (WASTE_PIECE_ID, WASTE_HISTORY_ID);

-- Unique Indexes
CREATE UNIQUE INDEX WPIEH_PIE_UK1_UK ON WASTE_PIECE_HISTORY (WASTE_STRATUM_ID, WASTE_HISTORY_ID, WASTE_PIECE_ID);
CREATE UNIQUE INDEX WPIEH_PIE_UK_UK ON WASTE_PIECE_HISTORY (WASTE_PLOT_ID, WASTE_HISTORY_ID, WASTE_PIECE_ID);

-- Foreign Keys (commented for later use)