-- DDL Migration for HBS_ENCRYPTION_KEY (DBeaver style)
-- Table columns
CREATE TABLE HBS_ENCRYPTION_KEY (
    HBS_ENCR_KEY_ID NUMBER(2,0) NOT NULL,
    DESCRIPTION VARCHAR2(30) NOT NULL,
    KEYSTORE_ALIAS VARCHAR2(256) NOT NULL,
    HBS_CRYPT_METHOD_ID NUMBER(2,0) NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30),
    UPDATE_TIMESTAMP DATE
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT SYS_C0017887 CHECK (HBS_ENCR_KEY_ID IS NOT NULL);
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT SYS_C0017888 CHECK (DESCRIPTION IS NOT NULL);
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT SYS_C0017889 CHECK (KEYSTORE_ALIAS IS NOT NULL);
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT SYS_C0017890 CHECK (HBS_CRYPT_METHOD_ID IS NOT NULL);
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT SYS_C0017891 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT SYS_C0017892 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT SYS_C0017893 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT SYS_C0017894 CHECK (ENTRY_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT HBS_ENCRYPTION_KEY_PK PRIMARY KEY (HBS_ENCR_KEY_ID);

-- Indexes
CREATE INDEX HEK_HCM_FK_I ON HBS_ENCRYPTION_KEY (HBS_CRYPT_METHOD_ID);

-- Foreign Keys (commented for later use)
