-- DDL Migration for WASTE_ASSESS_AREA_STS_AUDIT (DBeaver style)
-- Table columns
CREATE TABLE WASTE_ASSESS_AREA_STS_AUDIT (
    WASTE_ASSESSMENT_AREA_AUDIT_ID NUMBER(12,0) NOT NULL,
    WASTE_ASSESSMENT_AREA_ID NUMBER(12,0),
    WASTE_ASSESS_AREA_STS_CODE VARCHAR2(4) NOT NULL,
    WASTE_COMMENT VARCHAR2(2000),
    DOCUMENT_CONTROL_NUMBER NUMBER(10,0),
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT SYS_C0017727 CHECK (WASTE_ASSESSMENT_AREA_AUDIT_ID IS NOT NULL);
ALTER TABLE WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT SYS_C0017728 CHECK (WASTE_ASSESS_AREA_STS_CODE IS NOT NULL);
ALTER TABLE WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT SYS_C0017729 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT SYS_C0017730 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT SYS_C0017731 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT SYS_C0017732 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT WAASA_PK PRIMARY KEY (WASTE_ASSESSMENT_AREA_AUDIT_ID);

-- Indexes
CREATE INDEX WAASA_WAA_FK_I ON WASTE_ASSESS_AREA_STS_AUDIT (WASTE_ASSESSMENT_AREA_ID);
CREATE INDEX WAASA_WAASC_FK_I ON WASTE_ASSESS_AREA_STS_AUDIT (WASTE_ASSESS_AREA_STS_CODE);
CREATE INDEX WAASA_HSR_FK_I ON WASTE_ASSESS_AREA_STS_AUDIT (DOCUMENT_CONTROL_NUMBER);

-- Foreign Keys (commented for later use)
