-- Migration for THE.WASTE_MATURITY_TYPE_CODE

CREATE TABLE THE.WASTE_MATURITY_TYPE_CODE (
    WASTE_MATURITY_TYPE_CODE VARCHAR2(8) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT MATC_PK PRIMARY KEY (WASTE_MATURITY_TYPE_CODE),
    CONSTRAINT MATC_C1 CHECK (WASTE_MATURITY_TYPE_CODE IS NOT NULL),
    CONSTRAINT MATC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT MATC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT MATC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT MATC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
