-- DDL migration for THE.WASTE_MATERIAL_CLASS_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE WASTE_MATERIAL_CLASS_CODE (
    WASTE_MATERIAL_CLASS_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0031468 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0031469 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0031470 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0031471 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE WASTE_MATERIAL_CLASS_CODE ADD CONSTRAINT WMCC_PK PRIMARY KEY (WASTE_MATERIAL_CLASS_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
