-- Migration for THE.WASTE_CLASS_CODE

CREATE TABLE THE.WASTE_CLASS_CODE (
    WASTE_CLASS_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WCC_PK PRIMARY KEY (WASTE_CLASS_CODE),
    CONSTRAINT WCC_C1 CHECK (WASTE_CLASS_CODE IS NOT NULL),
    CONSTRAINT WCC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WCC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WCC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WCC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
