-- DDL migration for THE.SCALE_GRADE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE SCALE_GRADE_CODE (
    SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0029697 CHECK (SCALE_GRADE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0029698 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0029699 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029700 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029701 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE SCALE_GRADE_CODE ADD CONSTRAINT SYS_C0034834 PRIMARY KEY (SCALE_GRADE_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
