-- Migration for THE.INTERIOR_SCALE_GRADE_CODE

CREATE TABLE THE.INTERIOR_SCALE_GRADE_CODE (
    INTERIOR_SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT ISGC_C1 CHECK (INTERIOR_SCALE_GRADE_CODE IS NOT NULL),
    CONSTRAINT ISGC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT ISGC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT ISGC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT ISGC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- No primary key or unique index found for this table.
-- No foreign key constraints found for this table.
