-- DDL migration for HARVESTING_AUTHORITY (DBeaver style)
CREATE TABLE HARVESTING_AUTHORITY (
    HVA_SKEY NUMBER(10,0) NOT NULL,
    FOREST_FILE_ID VARCHAR2(10) NOT NULL,
    CUTTING_PERMIT_ID VARCHAR2(3),
    HARVESTING_AUTHORITY_ID VARCHAR2(30),
    FOREST_DISTRICT NUMBER(10,0) NOT NULL,
    DISTRICT_ADMN_ZONE VARCHAR2(4),
    GEOGRAPHIC_DISTRICT NUMBER(10,0) NOT NULL,
    MGMT_UNIT_ID VARCHAR2(4),
    MGMT_UNIT_TYPE_CODE VARCHAR2(1),
    LICENCE_TO_CUT_CODE VARCHAR2(2),
    HARVEST_TYPE_CODE VARCHAR2(1) NOT NULL,
    HARVEST_AUTH_STATUS_CODE VARCHAR2(3),
    TENURE_TERM NUMBER(5,0),
    STATUS_DATE DATE,
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    EXTEND_DATE DATE,
    EXTEND_COUNT NUMBER(10,0),
    HARVEST_AUTH_EXTEND_REAS_CODE VARCHAR2(1),
    QUOTA_TYPE_CODE VARCHAR2(1),
    CROWN_LANDS_REGION_CODE VARCHAR2(1),
    SALVAGE_TYPE_CODE VARCHAR2(3),
    CASCADE_SPLIT_CODE VARCHAR2(1),
    CATASTROPHIC_IND VARCHAR2(1),
    CROWN_GRANTED_IND VARCHAR2(1) NOT NULL,
    CRUISE_BASED_IND VARCHAR2(1) NOT NULL,
    DECIDUOUS_IND VARCHAR2(1) NOT NULL,
    BCAA_FOLIO_NUMBER VARCHAR2(23),
    LOCATION VARCHAR2(100),
    HIGHER_LEVEL_PLAN_REFERENCE VARCHAR2(30),
    HARVEST_AREA NUMBER(11,4),
    RETIREMENT_DATE DATE,
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    IS_WASTE_ASSESSMENT_REQUIRED VARCHAR2(1) NOT NULL,
    IS_CP_EXTENSN_APPL_FEE_WAIVED VARCHAR2(1) NOT NULL,
    IS_CP_EXTENSION_APPL_FEE_PAID VARCHAR2(1) NOT NULL,
    IS_WITHIN_FIBRE_RECOVERY_ZONE VARCHAR2(1) NOT NULL,
    HARVESTING_AUTHORITY_GUID RAW(16) NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0067187 CHECK (IS_WASTE_ASSESSMENT_REQUIRED IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0067188 CHECK (IS_CP_EXTENSN_APPL_FEE_WAIVED IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0067189 CHECK (IS_CP_EXTENSION_APPL_FEE_PAID IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0067190 CHECK (IS_WITHIN_FIBRE_RECOVERY_ZONE IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT HVA_IS_WASTE_ASSESS_REQ_CK CHECK (IS_WASTE_ASSESSMENT_REQUIRED IN ('Y', 'N', 'U'));
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT HVA_IS_CP_EXT_APPL_FEE_WA_CK CHECK (IS_CP_EXTENSN_APPL_FEE_WAIVED IN ('Y', 'N', 'U'));
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT HVA_IS_CP_EXT_APPL_FEE_PA_CK CHECK (IS_CP_EXTENSION_APPL_FEE_PAID IN ('Y', 'N', 'U'));
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT HVA_IS_WITHIN_FRZ_CK CHECK (IS_WITHIN_FIBRE_RECOVERY_ZONE IN ('Y', 'N', 'U'));
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C00111795 CHECK (HARVESTING_AUTHORITY_GUID IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT AVCON_1148331360_CATAS_000 CHECK (CATASTROPHIC_IND IN ('N', 'Y'));
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT AVCON_1148331360_CROWN_000 CHECK (CROWN_GRANTED_IND IN ('N', 'Y'));
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT AVCON_1148331360_CRUIS_000 CHECK (CRUISE_BASED_IND IN ('N', 'Y'));
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT AVCON_1148331360_DECID_000 CHECK (DECIDUOUS_IND IN ('N', 'Y'));
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028615 CHECK (HVA_SKEY IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028616 CHECK (FOREST_FILE_ID IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028617 CHECK (FOREST_DISTRICT IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028618 CHECK (GEOGRAPHIC_DISTRICT IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028620 CHECK (HARVEST_TYPE_CODE IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028622 CHECK (CROWN_GRANTED_IND IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028624 CHECK (CRUISE_BASED_IND IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028626 CHECK (DECIDUOUS_IND IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028628 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028629 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028630 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028631 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT SYS_C0028632 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE HARVESTING_AUTHORITY ADD CONSTRAINT HVA_PK PRIMARY KEY (HVA_SKEY);

-- Unique Indexes
CREATE UNIQUE INDEX HVA_GUID_UK ON HARVESTING_AUTHORITY (HARVESTING_AUTHORITY_GUID);
CREATE UNIQUE INDEX HVA_FF_CP_HVAID_UK ON HARVESTING_AUTHORITY (FOREST_FILE_ID, CUTTING_PERMIT_ID, HARVESTING_AUTHORITY_ID);

-- Non-unique Indexes
CREATE INDEX HVA_OU_FK_I ON HARVESTING_AUTHORITY (FOREST_DISTRICT);
CREATE INDEX HVA_LTCCD_FK_I ON HARVESTING_AUTHORITY (LICENCE_TO_CUT_CODE);
CREATE INDEX HVA_FF_CP_I ON HARVESTING_AUTHORITY (FOREST_FILE_ID, CUTTING_PERMIT_ID);
CREATE INDEX HVA_I1 ON HARVESTING_AUTHORITY (HARVEST_TYPE_CODE);

-- Foreign keys (to be added separately)