-- DDL migration for WASTE_TYPE_STRATUM_XREF (DBeaver style)
CREATE TABLE WASTE_TYPE_STRATUM_XREF (
    WASTE_TYPE_CODE VARCHAR2(3) NOT NULL,
    WASTE_STRATUM_TYPE_CODE VARCHAR2(3) NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_TYPE_STRATUM_XREF ADD CONSTRAINT SYS_C0027875 CHECK (WASTE_TYPE_CODE IS NOT NULL);
ALTER TABLE WASTE_TYPE_STRATUM_XREF ADD CONSTRAINT SYS_C0027877 CHECK (WASTE_STRATUM_TYPE_CODE IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_TYPE_STRATUM_XREF ADD CONSTRAINT WTSX_PK PRIMARY KEY (WASTE_TYPE_CODE, WASTE_STRATUM_TYPE_CODE);

-- Unique Index

-- Non-unique Indexes
CREATE INDEX WTSX_WSTC_FK_I ON WASTE_TYPE_STRATUM_XREF (WASTE_STRATUM_TYPE_CODE);
CREATE INDEX WTSX_WTC_FK_I ON WASTE_TYPE_STRATUM_XREF (WASTE_TYPE_CODE);

-- Foreign keys (to be added separately)