-- DDL migration for WASTE_ASSESSMENT_AREA (DBeaver style)
CREATE TABLE WASTE_ASSESSMENT_AREA (
    WASTE_ASSESSMENT_AREA_ID NUMBER(12,0) NOT NULL,
    PARENT_WAA_ID NUMBER(12,0),
    REPORTING_UNIT_ID NUMBER(12,0) NOT NULL,
    FOREST_FILE_ID VARCHAR2(10) NOT NULL,
    TIMBER_MARK VARCHAR2(6),
    CB_SKEY NUMBER(10,0),
    WASTE_MATURITY_TYPE_CODE VARCHAR2(8),
    WASTE_CONDITION_TYPE_CODE VARCHAR2(3),
    WASTE_SITE_TYPE_CODE VARCHAR2(2),
    WASTE_HARVEST_STATUS_CODE VARCHAR2(4),
    WASTE_NET_AREA NUMBER(5,2) NOT NULL,
    MARK_AREA NUMBER(5,2),
    REMAINING_HARVEST_AREA NUMBER(5,2),
    YEAR_LOGGED_FROM NUMBER(4,0),
    YEAR_LOGGED_TO NUMBER(4,0),
    PRIMARY_LOGGING_COMPLETE_DATE DATE,
    ASSESS_STATUS_CHANGE_DATE DATE,
    BENCHMARK_VOLUME NUMBER(2,0),
    WASTE_SURVEYOR_LICENCE VARCHAR2(4),
    RETURN_NUMBER VARCHAR2(4),
    WASTE_ROADS_AREA NUMBER(4,2),
    SURVEY_DATE DATE,
    CRUISE_VOLUME NUMBER(4,0),
    WASTE_ASSESS_AREA_STS_CODE VARCHAR2(4) NOT NULL,
    SURVEY_MAP_DOCUMENT_NAME VARCHAR2(50),
    SURVEY_MAP_MIME_TYPE_CODE VARCHAR2(3),
    PARENT_BLOCK_IND VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CHILD_BLOCK_IND VARCHAR2(1) DEFAULT 'N' NOT NULL,
    MULTI_MARK_IND VARCHAR2(1) DEFAULT 'N' NOT NULL,
    WASTE_PARENT_BLOCK_TYPE_CODE VARCHAR2(2),
    DOCUMENT_CONTROL_NUMBER NUMBER(10,0),
    HBS_EDIT_ERR_MESSAGE_CODE VARCHAR2(6),
    HBS_EDIT_ERR_CATEGORY_CODE VARCHAR2(3),
    DRAFT_TIMBER_MARK VARCHAR2(10),
    DRAFT_CUTTING_PERMIT_ID VARCHAR2(3),
    DRAFT_CUT_BLOCK_ID VARCHAR2(10),
    CUTTING_PERMIT_ID VARCHAR2(3),
    CUT_BLOCK_ID VARCHAR2(10),
    WASTE_SURVEY_CHECK_CODE VARCHAR2(3),
    NUMBER_OF_PLOTS_CHECKED NUMBER(3,0),
    WASTE_AREA_RISK_RATING_CODE VARCHAR2(3),
    INVOICE_NOTATION VARCHAR2(80),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    ERROR_EMAIL_TIMESTAMP DATE,
    OBLIGATION_ADJUSTMENT NUMBER(5,2),
    WASTE_FIBRE_RECOVERY_ZONE_RATE VARCHAR2(1)
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020713 CHECK (WASTE_ASSESSMENT_AREA_ID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020714 CHECK (REPORTING_UNIT_ID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020715 CHECK (FOREST_FILE_ID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020716 CHECK (WASTE_NET_AREA IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020717 CHECK (WASTE_ASSESS_AREA_STS_CODE IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020718 CHECK (PARENT_BLOCK_IND IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020719 CHECK (CHILD_BLOCK_IND IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020720 CHECK (MULTI_MARK_IND IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020721 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020722 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020723 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020724 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT SYS_C0020725 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_PK PRIMARY KEY (WASTE_ASSESSMENT_AREA_ID);

-- Unique Index

-- Non-unique Indexes
CREATE INDEX WAA_CBLK_FK_I ON WASTE_ASSESSMENT_AREA (CB_SKEY);
CREATE INDEX WAA_HAA_FK_I ON WASTE_ASSESSMENT_AREA (FOREST_FILE_ID);
CREATE INDEX WAA_HEEMC_FK_I ON WASTE_ASSESSMENT_AREA (HBS_EDIT_ERR_MESSAGE_CODE);
CREATE INDEX WAA_MTC_FK_I ON WASTE_ASSESSMENT_AREA (WASTE_MATURITY_TYPE_CODE);
CREATE INDEX WAA_SITC_FK_I ON WASTE_ASSESSMENT_AREA (WASTE_SITE_TYPE_CODE);
CREATE INDEX WAA_WAASC_FK_I ON WASTE_ASSESSMENT_AREA (WASTE_ASSESS_AREA_STS_CODE);
CREATE INDEX WAA_WCTC_FK_I ON WASTE_ASSESSMENT_AREA (WASTE_CONDITION_TYPE_CODE);
CREATE INDEX WAA_WRU_FK_I ON WASTE_ASSESSMENT_AREA (REPORTING_UNIT_ID);
CREATE INDEX WAA_WSCC_FK_I_1 ON WASTE_ASSESSMENT_AREA (WASTE_SURVEY_CHECK_CODE);

-- Foreign keys (to be added separately)