-- DDL migration for CUT_BLOCK (DBeaver style)
CREATE TABLE CUT_BLOCK (
    CB_SKEY NUMBER(10,0) NOT NULL,
    HVA_SKEY NUMBER(10,0),
    FOREST_FILE_ID VARCHAR2(10) NOT NULL,
    CUTTING_PERMIT_ID VARCHAR2(3),
    TIMBER_MARK VARCHAR2(10),
    CUT_BLOCK_ID VARCHAR2(10) NOT NULL,
    SP_EXEMPT_IND VARCHAR2(1) DEFAULT 'N' NOT NULL,
    BLOCK_STATUS_DATE DATE,
    CUT_BLOCK_DESCRIPTION VARCHAR2(120),
    CUT_REGULATION_CODE VARCHAR2(3),
    BLOCK_STATUS_ST VARCHAR2(3) NOT NULL,
    REFOREST_DECLARE_TYPE_CODE VARCHAR2(3),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    IS_WASTE_ASSESSMENT_REQUIRED VARCHAR2(1) DEFAULT 'U' NOT NULL,
    CUT_BLOCK_GUID RAW(16) DEFAULT SYS_GUID() NOT NULL,
    FIRE_HARVESTING_REASON_CODE VARCHAR2(10),
    IS_UNDER_PARTITION_ORDER VARCHAR2(1),
    REPORTED_FIRE_DATE DATE
);

-- Explicit CHECK constraints
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012353 CHECK (CB_SKEY IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012356 CHECK (FOREST_FILE_ID IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012359 CHECK (CUT_BLOCK_ID IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012362 CHECK (SP_EXEMPT_IND IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT AVCON_1054232647_SP_EX_000 CHECK (SP_EXEMPT_IND IN ('N', 'Y'));
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012365 CHECK (BLOCK_STATUS_ST IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012368 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012371 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012373 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012374 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0012375 CHECK (UPDATE_TIMESTAMP IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C00111793 CHECK (CUT_BLOCK_GUID IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT SYS_C0067185 CHECK (IS_WASTE_ASSESSMENT_REQUIRED IS NOT NULL);
ALTER TABLE CUT_BLOCK ADD CONSTRAINT CBLK_IS_WASTE_ASSESS_REQ_CK CHECK (IS_WASTE_ASSESSMENT_REQUIRED IN ('Y', 'N', 'U'));

-- Primary Key
ALTER TABLE CUT_BLOCK ADD CONSTRAINT CBLK_PK PRIMARY KEY (CB_SKEY);

-- Unique Indexes

-- Non-unique Indexes
CREATE INDEX CBLK1_I ON CUT_BLOCK (FOREST_FILE_ID);
CREATE INDEX CBLK2_I ON CUT_BLOCK (TIMBER_MARK);
CREATE INDEX CBLK_FF_TM_CB_I ON CUT_BLOCK (FOREST_FILE_ID, TIMBER_MARK, CUT_BLOCK_ID);
CREATE INDEX CBLK_I ON CUT_BLOCK (CUT_BLOCK_ID);

-- Foreign keys (to be added separately)
