-- DDL migration for THE.WASTE_DISPERSED_CV_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE WASTE_DISPERSED_CV_CODE (
    WASTE_DISPERSED_CV_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0023352 CHECK (WASTE_DISPERSED_CV_CODE IS NOT NULL),
    CONSTRAINT SYS_C0023354 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0023356 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0023358 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0023360 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE WASTE_DISPERSED_CV_CODE ADD CONSTRAINT WDCV_PK PRIMARY KEY (WASTE_DISPERSED_CV_CODE);

-- Indexes

-- No foreign keys found
-- DDL migration for THE.COAST_WMRF_GRADE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE COAST_WMRF_GRADE_CODE (
    COAST_WMRF_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0018772 CHECK (COAST_WMRF_GRADE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0018773 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0018774 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0018775 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0018776 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE COAST_WMRF_GRADE_CODE ADD CONSTRAINT CWGC_PK PRIMARY KEY (COAST_WMRF_GRADE_CODE);

-- Indexes

-- No foreign keys found
-- Migration for THE.WASTE_DESIGNATION_TYPE_CODE

CREATE TABLE THE.WASTE_DESIGNATION_TYPE_CODE (
    WASTE_DESIGNATION_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WDTC1_PK PRIMARY KEY (WASTE_DESIGNATION_TYPE_CODE),
    CONSTRAINT WDTC1_C1 CHECK (WASTE_DESIGNATION_TYPE_CODE IS NOT NULL),
    CONSTRAINT WDTC1_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WDTC1_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WDTC1_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WDTC1_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_SUBMITTER_ROLE_TYPE_CODE

CREATE TABLE THE.WASTE_SUBMITTER_ROLE_TYPE_CODE (
    WASTE_SUBMITTER_ROLE_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WSRTC_PK PRIMARY KEY (WASTE_SUBMITTER_ROLE_TYPE_CODE),
    CONSTRAINT WSRTC_C1 CHECK (WASTE_SUBMITTER_ROLE_TYPE_CODE IS NOT NULL),
    CONSTRAINT WSRTC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WSRTC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WSRTC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WSRTC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- DDL migration for THE.WASTE_SURVEY_CHECK_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE WASTE_SURVEY_CHECK_CODE (
    WASTE_SURVEY_CHECK_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0014886 CHECK (WASTE_SURVEY_CHECK_CODE IS NOT NULL),
    CONSTRAINT SYS_C0014887 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0014888 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0014889 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0014890 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE WASTE_SURVEY_CHECK_CODE ADD CONSTRAINT WSCC_PK PRIMARY KEY (WASTE_SURVEY_CHECK_CODE);

-- Indexes

-- No foreign keys found
-- DDL migration for WASTE_RATE_SOURCE_CODE (DBeaver style)
CREATE TABLE WASTE_RATE_SOURCE_CODE (
    WASTE_RATE_SOURCE_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018728 CHECK (WASTE_RATE_SOURCE_CODE IS NOT NULL);
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018729 CHECK (DESCRIPTION IS NOT NULL);
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018730 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018731 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018732 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT WRSC_PK PRIMARY KEY (WASTE_RATE_SOURCE_CODE);

-- Unique Index

-- No foreign keys found
-- DDL migration for WASTE_AREA_RISK_RATING_CODE (DBeaver style)
CREATE TABLE WASTE_AREA_RISK_RATING_CODE (
    WASTE_AREA_RISK_RATING_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023763 CHECK (WASTE_AREA_RISK_RATING_CODE IS NOT NULL);
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023764 CHECK (DESCRIPTION IS NOT NULL);
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023765 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023766 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT SYS_C0023767 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_AREA_RISK_RATING_CODE ADD CONSTRAINT WARRC_PK PRIMARY KEY (WASTE_AREA_RISK_RATING_CODE);

-- Unique Index

-- No foreign keys found
-- Migration for THE.WASTE_PARENT_BLOCK_TYPE_CODE

CREATE TABLE THE.WASTE_PARENT_BLOCK_TYPE_CODE (
    WASTE_PARENT_BLOCK_TYPE_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WPBTC_PK PRIMARY KEY (WASTE_PARENT_BLOCK_TYPE_CODE),
    CONSTRAINT WPBTC_C1 CHECK (WASTE_PARENT_BLOCK_TYPE_CODE IS NOT NULL),
    CONSTRAINT WPBTC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WPBTC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WPBTC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WPBTC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- DDL migration for THE.HBS_EDIT_ERR_MESSAGE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE HBS_EDIT_ERR_MESSAGE_CODE (
    HBS_EDIT_ERR_MESSAGE_CODE VARCHAR2(6) NOT NULL,
    HBS_EDIT_ERR_CATEGORY_CODE VARCHAR2(3) NOT NULL,
    HBS_EDIT_ERR_RESPONSIBLTY_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C007793 CHECK (HBS_EDIT_ERR_MESSAGE_CODE IS NOT NULL),
    CONSTRAINT SYS_C007794 CHECK (HBS_EDIT_ERR_CATEGORY_CODE IS NOT NULL),
    CONSTRAINT SYS_C007795 CHECK (HBS_EDIT_ERR_RESPONSIBLTY_CODE IS NOT NULL),
    CONSTRAINT SYS_C007796 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C007797 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C007798 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C007799 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE HBS_EDIT_ERR_MESSAGE_CODE ADD CONSTRAINT EEMC_PK PRIMARY KEY (HBS_EDIT_ERR_MESSAGE_CODE, HBS_EDIT_ERR_CATEGORY_CODE);

-- Indexes
CREATE INDEX EEMC_ECC_FK_I ON HBS_EDIT_ERR_MESSAGE_CODE (HBS_EDIT_ERR_CATEGORY_CODE);

-- Foreign Keys
-- DDL migration for THE.INTERIOR_WMRF_GRADE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE INTERIOR_WMRF_GRADE_CODE (
    INTERIOR_WMRF_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0018746 CHECK (INTERIOR_WMRF_GRADE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0018748 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0018750 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0018753 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0018756 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE INTERIOR_WMRF_GRADE_CODE ADD CONSTRAINT IWGC_PK PRIMARY KEY (INTERIOR_WMRF_GRADE_CODE);

-- Indexes

-- No foreign keys found
-- DDL migration for THE.WASTE_ACCUMULATED_CV_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE WASTE_ACCUMULATED_CV_CODE (
    WASTE_ACCUMULATED_CV_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0023371 CHECK (WASTE_ACCUMULATED_CV_CODE IS NOT NULL),
    CONSTRAINT SYS_C0023373 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0023375 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0023377 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0023379 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE WASTE_ACCUMULATED_CV_CODE ADD CONSTRAINT WACV_PK PRIMARY KEY (WASTE_ACCUMULATED_CV_CODE);

-- Indexes

-- No foreign keys found
-- Migration for THE.WASTE_CLASS_CODE

CREATE TABLE THE.WASTE_CLASS_CODE (
    WASTE_CLASS_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WCC_PK PRIMARY KEY (WASTE_CLASS_CODE),
    CONSTRAINT WCC_C1 CHECK (WASTE_CLASS_CODE IS NOT NULL),
    CONSTRAINT WCC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WCC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WCC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WCC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- DDL migration for THE.COAST_SCALE_GRADE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE COAST_SCALE_GRADE_CODE (
    COAST_SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0028314 CHECK (COAST_SCALE_GRADE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0028315 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0028316 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0028318 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0028320 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE COAST_SCALE_GRADE_CODE ADD CONSTRAINT CSGC_PK PRIMARY KEY (COAST_SCALE_GRADE_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
-- Migration for THE.WASTE_BILLING_STS_CODE

CREATE TABLE THE.WASTE_BILLING_STS_CODE (
    WASTE_BILLING_STS_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WBSC_PK PRIMARY KEY (WASTE_BILLING_STS_CODE),
    CONSTRAINT WBSC_C1 CHECK (WASTE_BILLING_STS_CODE IS NOT NULL),
    CONSTRAINT WBSC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WBSC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WBSC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WBSC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_MATERIAL_KIND_CODE

CREATE TABLE THE.WASTE_MATERIAL_KIND_CODE (
    WASTE_MATERIAL_KIND_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WMKC_PK PRIMARY KEY (WASTE_MATERIAL_KIND_CODE),
    CONSTRAINT WMKC_C1 CHECK (WASTE_MATERIAL_KIND_CODE IS NOT NULL),
    CONSTRAINT WMKC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WMKC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WMKC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WMKC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_PIECE_END_CODE

CREATE TABLE THE.WASTE_PIECE_END_CODE (
    WASTE_PIECE_END_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT PEC_PK PRIMARY KEY (WASTE_PIECE_END_CODE),
    CONSTRAINT PEC_C1 CHECK (WASTE_PIECE_END_CODE IS NOT NULL),
    CONSTRAINT PEC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT PEC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT PEC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT PEC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- No foreign key constraints found for this table.
-- DDL migration for DATA_SOURCE_CODE (DBeaver style)
CREATE TABLE DATA_SOURCE_CODE (
    DATA_SOURCE_CODE VARCHAR2(10) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015735 CHECK (DATA_SOURCE_CODE IS NOT NULL);
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015737 CHECK (DESCRIPTION IS NOT NULL);
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015739 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015740 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015742 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT DSC_PK PRIMARY KEY (DATA_SOURCE_CODE);

-- Unique Index

-- No foreign keys found
-- DDL migration for THE.MIME_TYPE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE MIME_TYPE_CODE (
    MIME_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0029748 CHECK (MIME_TYPE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0029749 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0029750 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029751 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029752 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE MIME_TYPE_CODE ADD CONSTRAINT SYS_C0034825 PRIMARY KEY (MIME_TYPE_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
-- Migration for THE.WASTE_LEVEL_CODE

CREATE TABLE THE.WASTE_LEVEL_CODE (
    WASTE_LEVEL_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WLC_PK PRIMARY KEY (WASTE_LEVEL_CODE),
    CONSTRAINT WLC_C1 CHECK (WASTE_LEVEL_CODE IS NOT NULL),
    CONSTRAINT WLC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WLC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WLC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WLC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.INTERIOR_SCALE_GRADE_CODE

CREATE TABLE THE.INTERIOR_SCALE_GRADE_CODE (
    INTERIOR_SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT ISGC_C1 CHECK (INTERIOR_SCALE_GRADE_CODE IS NOT NULL),
    CONSTRAINT ISGC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT ISGC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT ISGC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT ISGC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- No primary key or unique index found for this table.
-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_ASSESSMENT_METHOD_CODE

CREATE TABLE THE.WASTE_ASSESSMENT_METHOD_CODE (
    WASTE_ASSESSMENT_METHOD_CODE VARCHAR2(4) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WAMC_PK PRIMARY KEY (WASTE_ASSESSMENT_METHOD_CODE),
    CONSTRAINT WAMC_C1 CHECK (WASTE_ASSESSMENT_METHOD_CODE IS NOT NULL),
    CONSTRAINT WAMC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WAMC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WAMC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WAMC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_STRATUM_TYPE_CODE

CREATE TABLE THE.WASTE_STRATUM_TYPE_CODE (
    WASTE_STRATUM_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WSTC_PK PRIMARY KEY (WASTE_STRATUM_TYPE_CODE),
    CONSTRAINT WSTC_C1 CHECK (WASTE_STRATUM_TYPE_CODE IS NOT NULL),
    CONSTRAINT WSTC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WSTC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WSTC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WSTC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_ASSESS_AREA_STS_CODE

CREATE TABLE THE.WASTE_ASSESS_AREA_STS_CODE (
    WASTE_ASSESS_AREA_STS_CODE VARCHAR2(4) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WAASC_PK PRIMARY KEY (WASTE_ASSESS_AREA_STS_CODE),
    CONSTRAINT WAASC_C1 CHECK (WASTE_ASSESS_AREA_STS_CODE IS NOT NULL),
    CONSTRAINT WAASC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WAASC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WAASC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WAASC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- DDL migration for THE.SCALE_PRODUCT_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE SCALE_PRODUCT_CODE (
    SCALE_PRODUCT_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0029716 CHECK (SCALE_PRODUCT_CODE IS NOT NULL),
    CONSTRAINT SYS_C0029718 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0029721 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029724 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029727 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE SCALE_PRODUCT_CODE ADD CONSTRAINT SYS_C0034829 PRIMARY KEY (SCALE_PRODUCT_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
-- Migration for THE.WASTE_CONDITION_TYPE_CODE

CREATE TABLE THE.WASTE_CONDITION_TYPE_CODE (
    WASTE_CONDITION_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WCTC_PK PRIMARY KEY (WASTE_CONDITION_TYPE_CODE),
    CONSTRAINT WCTC_C1 CHECK (WASTE_CONDITION_TYPE_CODE IS NOT NULL),
    CONSTRAINT WCTC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WCTC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WCTC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WCTC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_SAMPLING_OPTION_CODE

CREATE TABLE THE.WASTE_SAMPLING_OPTION_CODE (
    WASTE_SAMPLING_OPTION_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WSOC_PK PRIMARY KEY (WASTE_SAMPLING_OPTION_CODE),
    CONSTRAINT WSOC_C1 CHECK (WASTE_SAMPLING_OPTION_CODE IS NOT NULL),
    CONSTRAINT WSOC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WSOC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WSOC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WSOC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_COMMENT_CODE

CREATE TABLE THE.WASTE_COMMENT_CODE (
    WASTE_COMMENT_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WACC_PK PRIMARY KEY (WASTE_COMMENT_CODE),
    CONSTRAINT WACC_C1 CHECK (WASTE_COMMENT_CODE IS NOT NULL),
    CONSTRAINT WACC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WACC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WACC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WACC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- DDL migration for THE.WASTE_MATERIAL_CLASS_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE WASTE_MATERIAL_CLASS_CODE (
    WASTE_MATERIAL_CLASS_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0031468 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0031469 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0031470 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0031471 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE WASTE_MATERIAL_CLASS_CODE ADD CONSTRAINT WMCC_PK PRIMARY KEY (WASTE_MATERIAL_CLASS_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
-- Migration for THE.WASTE_SITE_TYPE_CODE

CREATE TABLE THE.WASTE_SITE_TYPE_CODE (
    WASTE_SITE_TYPE_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WSITC_PK PRIMARY KEY (WASTE_SITE_TYPE_CODE),
    CONSTRAINT WSITC_C1 CHECK (WASTE_SITE_TYPE_CODE IS NOT NULL),
    CONSTRAINT WSITC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WSITC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WSITC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WSITC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- DDL migration for THE.SCALE_SPECIES_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE SCALE_SPECIES_CODE (
    SCALE_SPECIES_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0029653 CHECK (SCALE_SPECIES_CODE IS NOT NULL),
    CONSTRAINT SYS_C0029654 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0029655 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029656 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029657 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE SCALE_SPECIES_CODE ADD CONSTRAINT SYS_C0034838 PRIMARY KEY (SCALE_SPECIES_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
-- Migration for THE.WASTE_MATURITY_TYPE_CODE

CREATE TABLE THE.WASTE_MATURITY_TYPE_CODE (
    WASTE_MATURITY_TYPE_CODE VARCHAR2(8) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT MATC_PK PRIMARY KEY (WASTE_MATURITY_TYPE_CODE),
    CONSTRAINT MATC_C1 CHECK (WASTE_MATURITY_TYPE_CODE IS NOT NULL),
    CONSTRAINT MATC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT MATC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT MATC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT MATC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_DECAY_TYPE_CODE

CREATE TABLE THE.WASTE_DECAY_TYPE_CODE (
    WASTE_DECAY_TYPE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT DTC_PK PRIMARY KEY (WASTE_DECAY_TYPE_CODE),
    CONSTRAINT DTC_C1 CHECK (WASTE_DECAY_TYPE_CODE IS NOT NULL),
    CONSTRAINT DTC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT DTC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT DTC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT DTC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_HARVEST_METHOD_CODE

CREATE TABLE THE.WASTE_HARVEST_METHOD_CODE (
    WASTE_HARVEST_METHOD_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WHMC_PK PRIMARY KEY (WASTE_HARVEST_METHOD_CODE),
    CONSTRAINT WHMC_C1 CHECK (WASTE_HARVEST_METHOD_CODE IS NOT NULL),
    CONSTRAINT WHMC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WHMC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WHMC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WHMC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- No foreign key constraints found for this table.
-- DDL migration for THE.SCALE_GRADE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE SCALE_GRADE_CODE (
    SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0029697 CHECK (SCALE_GRADE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0029698 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0029699 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029700 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029701 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE SCALE_GRADE_CODE ADD CONSTRAINT SYS_C0034834 PRIMARY KEY (SCALE_GRADE_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
-- Migration for THE.WASTE_TYPE_CODE

CREATE TABLE THE.WASTE_TYPE_CODE (
    WASTE_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WATC_PK PRIMARY KEY (WASTE_TYPE_CODE),
    CONSTRAINT WATC_C1 CHECK (WASTE_TYPE_CODE IS NOT NULL),
    CONSTRAINT WATC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WATC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WATC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WATC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_BORDERLINE_CODE

CREATE TABLE THE.WASTE_BORDERLINE_CODE (
    WASTE_BORDERLINE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT BC_PK PRIMARY KEY (WASTE_BORDERLINE_CODE),
    CONSTRAINT BC_C1 CHECK (WASTE_BORDERLINE_CODE IS NOT NULL),
    CONSTRAINT BC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT BC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT BC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT BC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
-- Migration for THE.WASTE_PLOT_SIZE_CODE

CREATE TABLE THE.WASTE_PLOT_SIZE_CODE (
    WASTE_PLOT_SIZE_CODE NUMBER(22) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT PSC_PK PRIMARY KEY (WASTE_PLOT_SIZE_CODE),
    CONSTRAINT PSC_C1 CHECK (WASTE_PLOT_SIZE_CODE IS NOT NULL),
    CONSTRAINT PSC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT PSC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT PSC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT PSC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
