-- DDL migration for THE.COAST_WMRF_GRADE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE COAST_WMRF_GRADE_CODE (
    COAST_WMRF_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0018772 CHECK (COAST_WMRF_GRADE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0018773 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0018774 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0018775 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0018776 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE COAST_WMRF_GRADE_CODE ADD CONSTRAINT CWGC_PK PRIMARY KEY (COAST_WMRF_GRADE_CODE);

-- Indexes

-- No foreign keys found
