-- Migration for THE.WASTE_SUBMITTER_ROLE_TYPE_CODE

CREATE TABLE THE.WASTE_SUBMITTER_ROLE_TYPE_CODE (
    WASTE_SUBMITTER_ROLE_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WSRTC_PK PRIMARY KEY (WASTE_SUBMITTER_ROLE_TYPE_CODE),
    CONSTRAINT WSRTC_C1 CHECK (WASTE_SUBMITTER_ROLE_TYPE_CODE IS NOT NULL),
    CONSTRAINT WSRTC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WSRTC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WSRTC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WSRTC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
