-- DDL migration for WASTE_RATE_SOURCE_CODE (DBeaver style)
CREATE TABLE WASTE_RATE_SOURCE_CODE (
    WASTE_RATE_SOURCE_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018728 CHECK (WASTE_RATE_SOURCE_CODE IS NOT NULL);
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018729 CHECK (DESCRIPTION IS NOT NULL);
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018730 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018731 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT SYS_C0018732 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_RATE_SOURCE_CODE ADD CONSTRAINT WRSC_PK PRIMARY KEY (WASTE_RATE_SOURCE_CODE);

-- Unique Index

-- No foreign keys found
