-- Migration for THE.WASTE_PARENT_BLOCK_TYPE_CODE

CREATE TABLE THE.WASTE_PARENT_BLOCK_TYPE_CODE (
    WASTE_PARENT_BLOCK_TYPE_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WPBTC_PK PRIMARY KEY (WASTE_PARENT_BLOCK_TYPE_CODE),
    CONSTRAINT WPBTC_C1 CHECK (WASTE_PARENT_BLOCK_TYPE_CODE IS NOT NULL),
    CONSTRAINT WPBTC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WPBTC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WPBTC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WPBTC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
