-- DDL migration for THE.WASTE_DISPERSED_CV_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE WASTE_DISPERSED_CV_CODE (
    WASTE_DISPERSED_CV_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0023352 CHECK (WASTE_DISPERSED_CV_CODE IS NOT NULL),
    CONSTRAINT SYS_C0023354 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0023356 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0023358 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0023360 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE WASTE_DISPERSED_CV_CODE ADD CONSTRAINT WDCV_PK PRIMARY KEY (WASTE_DISPERSED_CV_CODE);

-- Indexes

-- No foreign keys found
