-- DDL migration for THE.WASTE_SURVEY_CHECK_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE WASTE_SURVEY_CHECK_CODE (
    WASTE_SURVEY_CHECK_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0014886 CHECK (WASTE_SURVEY_CHECK_CODE IS NOT NULL),
    CONSTRAINT SYS_C0014887 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0014888 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0014889 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0014890 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE WASTE_SURVEY_CHECK_CODE ADD CONSTRAINT WSCC_PK PRIMARY KEY (WASTE_SURVEY_CHECK_CODE);

-- Indexes

-- No foreign keys found
