-- DDL Migration for WASTE_PIECE (DBeaver style)
-- Table columns
CREATE TABLE WASTE_PIECE (
    WASTE_PIECE_ID NUMBER(12,0) NOT NULL,
    WASTE_PLOT_ID NUMBER(12,0),
    WASTE_STRATUM_ID NUMBER(12,0),
    WASTE_PIECE_NUMBER NUMBER(3,0) NOT NULL,
    WASTE_MATERIAL_KIND_CODE VARCHAR2(1) NOT NULL,
    WASTE_CLASS_CODE VARCHAR2(1) NOT NULL,
    SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    SCALE_PRODUCT_CODE VARCHAR2(2) NOT NULL,
    SCALE_SPECIES_CODE VARCHAR2(2) NOT NULL,
    LENGTH NUMBER(3,0),
    TOP_DIAMETER NUMBER(3,0),
    TOP_END_CODE VARCHAR2(1),
    BUTT_DIAMETER NUMBER(3,0),
    BUTT_END_CODE VARCHAR2(1),
    WASTE_BORDERLINE_CODE VARCHAR2(1),
    TOP_DEDUCTION NUMBER(3,0),
    BUTT_DEDUCTION NUMBER(3,0),
    WASTE_DECAY_TYPE_CODE VARCHAR2(1),
    WASTE_COMMENT_CODE VARCHAR2(2),
    ESTIMATED_VOLUME NUMBER(8,3),
    ESTIMATED_PERCENT NUMBER(4,1),
    DENSITY_ESTIMATE NUMBER(8,3),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    LENGTH_DEDUCTION NUMBER(3,0)
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018445 CHECK (WASTE_PIECE_ID IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018447 CHECK (WASTE_PIECE_NUMBER IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018449 CHECK (WASTE_MATERIAL_KIND_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018451 CHECK (WASTE_CLASS_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018453 CHECK (SCALE_GRADE_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018455 CHECK (SCALE_PRODUCT_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018457 CHECK (SCALE_SPECIES_CODE IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018459 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018461 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018463 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018464 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_PIECE ADD CONSTRAINT SYS_C0018465 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_PIECE ADD CONSTRAINT WPIE_PK PRIMARY KEY (WASTE_PIECE_ID);

-- Indexes
CREATE INDEX WPIE_BC_FK_I ON WASTE_PIECE (WASTE_BORDERLINE_CODE);
CREATE INDEX WPIE_DTC_FK_I ON WASTE_PIECE (WASTE_DECAY_TYPE_CODE);
CREATE INDEX WPIE_PEC_FK_I ON WASTE_PIECE (BUTT_END_CODE, TOP_END_CODE);
CREATE INDEX WPIE_SPGX_FK_I ON WASTE_PIECE (SCALE_GRADE_CODE, SCALE_PRODUCT_CODE, SCALE_SPECIES_CODE);
CREATE INDEX WPIE_WACC_FK_I ON WASTE_PIECE (WASTE_COMMENT_CODE);
CREATE INDEX WPIE_WCC_FK_I ON WASTE_PIECE (WASTE_CLASS_CODE);
CREATE INDEX WPIE_WPLO_FK_I ON WASTE_PIECE (WASTE_PLOT_ID);
CREATE INDEX WPIE_WSTR_FK_I ON WASTE_PIECE (WASTE_STRATUM_ID);
CREATE INDEX WPIBUTT_END_CODE_IDENTIFIED__I ON WASTE_PIECE (BUTT_END_CODE);

-- Foreign Keys (commented for later use)