-- DDL Migration for SPECIES_PRODUCT_GRADE_XREF (DBeaver style)
-- Table columns
CREATE TABLE SPECIES_PRODUCT_GRADE_XREF (
    SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    SCALE_SPECIES_CODE VARCHAR2(2) NOT NULL,
    SCALE_PRODUCT_CODE VARCHAR2(2) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SYS_C0025056 CHECK (SCALE_GRADE_CODE IS NOT NULL);
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SYS_C0025057 CHECK (SCALE_SPECIES_CODE IS NOT NULL);
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SYS_C0025058 CHECK (SCALE_PRODUCT_CODE IS NOT NULL);
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SYS_C0025059 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SYS_C0025060 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SYS_C0025061 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SSPGXREF_PK PRIMARY KEY (SCALE_GRADE_CODE, SCALE_SPECIES_CODE, SCALE_PRODUCT_CODE);

-- Indexes
CREATE INDEX SSPGXREF_HBS_SGC_FK_I ON SPECIES_PRODUCT_GRADE_XREF (SCALE_GRADE_CODE);
CREATE INDEX SSPGXREF_HBS_SSC_FK_I ON SPECIES_PRODUCT_GRADE_XREF (SCALE_SPECIES_CODE);
CREATE INDEX SSPGXREF_HBS_SPC_FK_I ON SPECIES_PRODUCT_GRADE_XREF (SCALE_PRODUCT_CODE);

-- Foreign Keys (commented for later use)
