-- DDL Migration for HBS_RSA_PADDING_SCHEME (DBeaver style)
-- Table columns
CREATE TABLE HBS_RSA_PADDING_SCHEME (
    HBS_RSA_PADDING_ID NUMBER(2,0) NOT NULL,
    DESCRIPTION VARCHAR2(30) NOT NULL,
    JAVA_CIPHER VARCHAR2(100) NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30),
    UPDATE_TIMESTAMP DATE
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE HBS_RSA_PADDING_SCHEME ADD CONSTRAINT SYS_C0017901 CHECK (HBS_RSA_PADDING_ID IS NOT NULL);
ALTER TABLE HBS_RSA_PADDING_SCHEME ADD CONSTRAINT SYS_C0017902 CHECK (DESCRIPTION IS NOT NULL);
ALTER TABLE HBS_RSA_PADDING_SCHEME ADD CONSTRAINT SYS_C0017903 CHECK (JAVA_CIPHER IS NOT NULL);
ALTER TABLE HBS_RSA_PADDING_SCHEME ADD CONSTRAINT SYS_C0017904 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE HBS_RSA_PADDING_SCHEME ADD CONSTRAINT SYS_C0017905 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE HBS_RSA_PADDING_SCHEME ADD CONSTRAINT SYS_C0017906 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE HBS_RSA_PADDING_SCHEME ADD CONSTRAINT SYS_C0017907 CHECK (ENTRY_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE HBS_RSA_PADDING_SCHEME ADD CONSTRAINT HBS_RSA_PADDING_SCHEME_PK PRIMARY KEY (HBS_RSA_PADDING_ID);

-- Indexes
