-- DDL Migration for HBS_SCALER_AUTH_KEY (DBeaver style)
-- Table columns
CREATE TABLE HBS_SCALER_AUTH_KEY (
    UPDATE_USERID VARCHAR2(30),
    UPDATE_TIMESTAMP DATE,
    HSAK_ID NUMBER(32,0) NOT NULL,
    USER_ID VARCHAR2(30),
    CLIENT_NUMBER VARCHAR2(8) NOT NULL,
    ENCRYPTED_AUTHENTICATION_KEY RAW(64) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE HBS_SCALER_AUTH_KEY ADD CONSTRAINT SYS_C0017854 CHECK (HSAK_ID IS NOT NULL);
ALTER TABLE HBS_SCALER_AUTH_KEY ADD CONSTRAINT SYS_C0017855 CHECK (CLIENT_NUMBER IS NOT NULL);
ALTER TABLE HBS_SCALER_AUTH_KEY ADD CONSTRAINT SYS_C0017856 CHECK (ENCRYPTED_AUTHENTICATION_KEY IS NOT NULL);
ALTER TABLE HBS_SCALER_AUTH_KEY ADD CONSTRAINT SYS_C0017857 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE HBS_SCALER_AUTH_KEY ADD CONSTRAINT SYS_C0017858 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE HBS_SCALER_AUTH_KEY ADD CONSTRAINT SYS_C0017859 CHECK (ENTRY_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE HBS_SCALER_AUTH_KEY ADD CONSTRAINT SAKEHT_PK PRIMARY KEY (HSAK_ID);

-- Unique Indexes
CREATE UNIQUE INDEX SAKEHT_AUTHKEY_UK ON HBS_SCALER_AUTH_KEY (CLIENT_NUMBER, EFFECTIVE_DATE);

-- Non-unique Indexes
CREATE INDEX SAKEHT_HBS_HU_FK_I ON HBS_SCALER_AUTH_KEY (USER_ID);

-- Foreign Keys (commented for later use)
