-- DDL Migration for WASTE_PLOT_HISTORY (DBeaver style)
-- Table columns
CREATE TABLE WASTE_PLOT_HISTORY (
    WASTE_PLOT_NUMBER NUMBER(3,0) NOT NULL,
    WASTE_BASELINE VARCHAR2(1),
    WASTE_STRIP NUMBER(2,0),
    MEASURE_FACTOR NUMBER(3,0) NOT NULL,
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    WASTE_PLOT_ID NUMBER(12,0) NOT NULL,
    WASTE_HISTORY_ID NUMBER(12,0) NOT NULL,
    WASTE_STRATUM_ID NUMBER(12,0) NOT NULL
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020592 CHECK (WASTE_PLOT_ID IS NOT NULL);
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020593 CHECK (WASTE_HISTORY_ID IS NOT NULL);
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020594 CHECK (WASTE_STRATUM_ID IS NOT NULL);
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020595 CHECK (WASTE_PLOT_NUMBER IS NOT NULL);
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020596 CHECK (MEASURE_FACTOR IS NOT NULL);
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020597 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020598 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020599 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020601 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT SYS_C0020602 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT WPLOH_PK PRIMARY KEY (WASTE_PLOT_ID, WASTE_HISTORY_ID);

-- Unique Index
CREATE UNIQUE INDEX WPLOH_UK ON WASTE_PLOT_HISTORY (WASTE_STRIP, WASTE_STRATUM_ID, WASTE_HISTORY_ID, WASTE_PLOT_ID);

-- Foreign Keys (commented for later use)