-- DDL Migration for WASTE_SPONSOR (DBeaver style)
-- Table columns
CREATE TABLE WASTE_SPONSOR (
    PERSONALLY_SUPERVISED_IND VARCHAR2(1),
    PERSONALLY_REVIEWED_IND VARCHAR2(1),
    WASTE_RELIEF_IND VARCHAR2(1),
    RATIONALE_REQUIRED_IND VARCHAR2(1),
    BURNT_PILES_IND VARCHAR2(1),
    FAX VARCHAR2(12),
    EMAIL VARCHAR2(100),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    WASTE_SPONSOR_ID NUMBER(12,0) NOT NULL,
    WASTE_ASSESSMENT_AREA_ID NUMBER(12,0),
    WASTE_SUBMITTER_ROLE_TYPE_CODE VARCHAR2(3) NOT NULL,
    SURVEYOR_SCALER_LICENSE_NUMBER VARCHAR2(5),
    PERSONALLY_COMPLETED_IND VARCHAR2(1),
    SPONSORED_BY_RFP_RFT_IND VARCHAR2(1),
    WASTE_DESIGNATION_TYPE_CODE VARCHAR2(3),
    LICENSE_NUMBER VARCHAR2(5),
    NAME VARCHAR2(80),
    PHONE VARCHAR2(12)
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT SYS_C0020802 CHECK (WASTE_SPONSOR_ID IS NOT NULL);
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT SYS_C0020803 CHECK (WASTE_SUBMITTER_ROLE_TYPE_CODE IS NOT NULL);
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT SYS_C0020804 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT SYS_C0020805 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT SYS_C0020806 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT SYS_C0020807 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT SYS_C0020808 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT WS_PK PRIMARY KEY (WASTE_SPONSOR_ID);

-- Indexes
CREATE INDEX WS_WAA_FK_I ON WASTE_SPONSOR (WASTE_ASSESSMENT_AREA_ID);
CREATE INDEX WS_WSRTC_FK_I ON WASTE_SPONSOR (WASTE_SUBMITTER_ROLE_TYPE_CODE);
CREATE INDEX WS_WDTC1_FK_I ON WASTE_SPONSOR (WASTE_DESIGNATION_TYPE_CODE);

-- Foreign Keys (commented for later use)