-- DDL Migration for WEIGH_SLIP (DBeaver style)
-- Table columns
CREATE TABLE WEIGH_SLIP (
    DETAIL_DOCUMENT_NUMBER VARCHAR2(13) NOT NULL,
    VERSION NUMBER(2,0) NOT NULL,
    BATDOC_ID NUMBER(32,0),
    SCALE_EVENT_TYPE_CODE VARCHAR2(2) NOT NULL,
    SCL_RTN_VERSION_STATE_CODE VARCHAR2(3) NOT NULL,
    SCALE_DATE DATE NOT NULL,
    SCALE_SITE_ID_NMBR VARCHAR2(4),
    CUT_BLOCK_ID VARCHAR2(10),
    POPULATION_NUMBER VARCHAR2(4),
    STRATUM_NUMBER VARCHAR2(2),
    SAMPLING_YEAR NUMBER(5,0),
    TIMBER_MARK VARCHAR2(6),
    TIMBER_BRAND VARCHAR2(7),
    COMPANY_USE_STRATUM VARCHAR2(8),
    PRIMARY_QUANT_LIC_TYPE_CD VARCHAR2(1),
    PRIMARY_LICENSE_NUMBER VARCHAR2(4),
    SECONDARY_QUANT_LIC_TYPE_CD VARCHAR2(1),
    SECONDARY_LICENSE_NUMBER VARCHAR2(4),
    SIGNING_QUANT_LIC_TYPE_CD VARCHAR2(1),
    SIGNING_LICENSE_NUMBER VARCHAR2(4),
    WEIGH_SLIP_NUMBER VARCHAR2(10) NOT NULL,
    GROSS_WEIGHT NUMBER(6,0),
    HBS_SAMPLE_TYPE_CODE VARCHAR2(1),
    TARE_WEIGHT NUMBER(6,0),
    SAMPLE_DEDUCTION_WEIGHT NUMBER(6,0),
    ORIGINAL_VERSION_IND VARCHAR2(1) NOT NULL,
    VALID_SIGNATURE_IND VARCHAR2(1) NOT NULL,
    ACTIVE_VERSION_IND VARCHAR2(1) NOT NULL,
    FIELD_SCALE_IND VARCHAR2(1),
    FIELD_SCALE_DECK_ID VARCHAR2(1),
    TRANSPORT_IDENTIFIER VARCHAR2(16),
    INCOMING_LDS_NUMBER VARCHAR2(10),
    OUTGOING_LDS_NUMBER VARCHAR2(10),
    DESTINATION VARCHAR2(4),
    WEIGH_SLIP_COMMENT VARCHAR2(240),
    DTL_DOC_SEQ NUMBER(32,0) NOT NULL,
    INPUT_SECONDARY_SCALER_LIC VARCHAR2(4),
    INPUT_CUTBLOCK_ID VARCHAR2(10),
    INPUT_PRIMARY_SCALER_LIC VARCHAR2(4),
    INPUT_SOURCE VARCHAR2(7),
    INPUT_PSY VARCHAR2(8),
    INPUT_SCALE_SITE VARCHAR2(4),
    INPUT_SIGNING_SCALER_LIC VARCHAR2(4),
    ENCRYPTED_SIGNATURE RAW(512),
    HBS_ENCR_KEY_ID NUMBER(2,0),
    INPUT_HBS_ENCR_KEY_ID NUMBER(2,0),
    HBS_RSA_PADDING_ID NUMBER(2,0),
    DECRYPTED_SIGNATURE VARCHAR2(128),
    HASH_TOTAL VARCHAR2(128),
    HBS_CRYPT_METHOD_ID NUMBER(2,0),
    SIGNING_DATE_TIME DATE,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30),
    UPDATE_TIMESTAMP DATE
);

-- Explicit CHECK constraints (NOT NULL and other conditions)
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017831 CHECK (DETAIL_DOCUMENT_NUMBER IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017832 CHECK (VERSION IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017833 CHECK (SCALE_EVENT_TYPE_CODE IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017834 CHECK (SCL_RTN_VERSION_STATE_CODE IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017835 CHECK (SCALE_DATE IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017836 CHECK (WEIGH_SLIP_NUMBER IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017837 CHECK (ORIGINAL_VERSION_IND IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017838 CHECK (VALID_SIGNATURE_IND IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017839 CHECK (ACTIVE_VERSION_IND IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017840 CHECK (DTL_DOC_SEQ IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017841 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0017842 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0039054 CHECK (FIELD_SCALE_IND IN ('Y', 'N'));
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0039089 CHECK (ORIGINAL_VERSION_IND IN ('Y', 'N'));
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0039029 CHECK (ACTIVE_VERSION_IND IN ('Y', 'N'));
-- Additional complex check constraints omitted for brevity

-- Primary Key
ALTER TABLE WEIGH_SLIP ADD CONSTRAINT SYS_C0039569 PRIMARY KEY (DETAIL_DOCUMENT_NUMBER, VERSION);

-- Indexes
CREATE INDEX WST_HRPS_FK_I ON WEIGH_SLIP (HBS_RSA_PADDING_ID);
CREATE INDEX WST_HCM_FK_I ON WEIGH_SLIP (HBS_CRYPT_METHOD_ID);
CREATE INDEX WST_HEK_FK1_I ON WEIGH_SLIP (HBS_ENCR_KEY_ID);
CREATE INDEX WSDR_PRIMARY_QL_FK_I ON WEIGH_SLIP (PRIMARY_LICENSE_NUMBER);
CREATE INDEX WSDR_MOF_TM_FK_I ON WEIGH_SLIP (TIMBER_MARK);
CREATE INDEX WSDR_SETC_FK_I ON WEIGH_SLIP (SCALE_EVENT_TYPE_CODE);
CREATE INDEX WSDR_VER_STATUS_FK_I ON WEIGH_SLIP (SCL_RTN_VERSION_STATE_CODE);
CREATE INDEX WSDR_DTLSCLDOC_FK_I ON WEIGH_SLIP (DETAIL_DOCUMENT_NUMBER);
CREATE INDEX WSDR_MOF_SS_FK_I ON WEIGH_SLIP (SCALE_SITE_ID_NMBR);
CREATE INDEX WSDR_PSYM_I ON WEIGH_SLIP (INPUT_PSY);
CREATE INDEX WSDR_BATDOC_FK_I ON WEIGH_SLIP (BATDOC_ID);
-- Additional indexes omitted for brevity

-- Foreign Keys (commented for later use)
