-- DDL Migration for WASTE_ASSESSMENT_SEGREGATION (DBeaver style)
-- Table columns
CREATE TABLE WASTE_ASSESSMENT_SEGREGATION (
    SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    SCALE_PRODUCT_CODE VARCHAR2(2) NOT NULL,
    SCALE_SPECIES_CODE VARCHAR2(2) NOT NULL,
    WASTE_ASSESSMENT_AREA_ID NUMBER(12,0) NOT NULL,
    ESTIMATED_VOLUME NUMBER(9,3) NOT NULL,
    RATE NUMBER NOT NULL,
    AVOIDABLE_IND VARCHAR2(1) NOT NULL,
    NUMBER_OF_PIECES NUMBER(6,0) NOT NULL
);

-- Explicit CHECK constraints (NOT NULL and other conditions)
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT SYS_C0018699 CHECK (SCALE_GRADE_CODE IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT SYS_C0018700 CHECK (SCALE_PRODUCT_CODE IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT SYS_C0018701 CHECK (SCALE_SPECIES_CODE IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT SYS_C0018702 CHECK (WASTE_ASSESSMENT_AREA_ID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT SYS_C0018703 CHECK (ESTIMATED_VOLUME IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT SYS_C0018704 CHECK (RATE IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT SYS_C0018705 CHECK (AVOIDABLE_IND IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT SYS_C0018706 CHECK (NUMBER_OF_PIECES IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT WAS_AI_CHK CHECK (AVOIDABLE_IND IN ('N', 'Y'));

-- Primary Key
ALTER TABLE WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT WAS_PK PRIMARY KEY (SCALE_GRADE_CODE, SCALE_PRODUCT_CODE, SCALE_SPECIES_CODE, WASTE_ASSESSMENT_AREA_ID, AVOIDABLE_IND);

-- Indexes
CREATE INDEX WAS_WAA_FK_I ON WASTE_ASSESSMENT_SEGREGATION (WASTE_ASSESSMENT_AREA_ID);
CREATE INDEX WAS_SPGX_FK_I ON WASTE_ASSESSMENT_SEGREGATION (SCALE_GRADE_CODE, SCALE_PRODUCT_CODE, SCALE_SPECIES_CODE);

-- Foreign Keys (commented for later use)
