-- DDL Migration for WASTE_STRATUM_HISTORY (DBeaver style)
-- Table columns
CREATE TABLE WASTE_STRATUM_HISTORY (
    WASTE_STRATUM_ID NUMBER(12,0) NOT NULL,
    WASTE_HISTORY_ID NUMBER(12,0) NOT NULL,
    WASTE_STRATUM_TYPE_CODE VARCHAR2(3) NOT NULL,
    WASTE_TYPE_CODE VARCHAR2(3),
    WASTE_HARVEST_METHOD_CODE VARCHAR2(2),
    WASTE_ASSESSMENT_METHOD_CODE VARCHAR2(4) NOT NULL,
    WASTE_PLOT_SIZE_CODE NUMBER(5,0),
    WASTE_LEVEL_CODE VARCHAR2(1),
    STRATUM_AREA NUMBER(5,2) NOT NULL,
    TOTAL_ESTIMATED_VOLUME NUMBER(5,0),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020567 CHECK (WASTE_STRATUM_ID IS NOT NULL);
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020569 CHECK (WASTE_HISTORY_ID IS NOT NULL);
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020570 CHECK (WASTE_STRATUM_TYPE_CODE IS NOT NULL);
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020571 CHECK (WASTE_ASSESSMENT_METHOD_CODE IS NOT NULL);
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020572 CHECK (STRATUM_AREA IS NOT NULL);
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020573 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020574 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020575 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020576 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT SYS_C0020577 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT WSTRAH_PK PRIMARY KEY (WASTE_HISTORY_ID, WASTE_STRATUM_ID);

-- Indexes

-- Foreign Keys (commented for later use)