-- DDL Migration for WASTE_RESIDUE_RATE (DBeaver style)
-- Table columns
CREATE TABLE WASTE_RESIDUE_RATE (
    WSTRT_ID NUMBER(32,0) NOT NULL,
    TIMBER_MARK VARCHAR2(6) NOT NULL,
    CUT_BLOCK_ID VARCHAR2(10) NOT NULL,
    SCALE_SPECIES_CODE VARCHAR2(2) NOT NULL,
    SCALE_PRODUCT_CODE VARCHAR2(2) NOT NULL,
    SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    WASTE_RATE_SOURCE_CODE VARCHAR2(2),
    ACTIVE_IND VARCHAR2(1) NOT NULL,
    AVOIDABLE_IND VARCHAR2(1) NOT NULL,
    RAW_RATE NUMBER(5,2),
    RATE NUMBER(5,2) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30),
    UPDATE_TIMESTAMP DATE
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020536 CHECK (WSTRT_ID IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020537 CHECK (TIMBER_MARK IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020538 CHECK (CUT_BLOCK_ID IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020539 CHECK (SCALE_SPECIES_CODE IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020540 CHECK (SCALE_PRODUCT_CODE IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020541 CHECK (SCALE_GRADE_CODE IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020542 CHECK (ACTIVE_IND IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020543 CHECK (AVOIDABLE_IND IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020544 CHECK (RATE IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020545 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020546 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020547 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT SYS_C0020548 CHECK (ENTRY_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_RESIDUE_RATE ADD CONSTRAINT WSTRATE_PK PRIMARY KEY (WSTRT_ID);

-- Indexes
CREATE INDEX WRR_HAA_FK_I ON WASTE_RESIDUE_RATE (TIMBER_MARK);
CREATE INDEX WRR_WRSC_FK_I ON WASTE_RESIDUE_RATE (WASTE_RATE_SOURCE_CODE);
CREATE INDEX WSTRATE_CUTBLK_FK_I ON WASTE_RESIDUE_RATE (CUT_BLOCK_ID);
CREATE INDEX WSTRATE_HBS_SGC_FK_I ON WASTE_RESIDUE_RATE (SCALE_GRADE_CODE);
CREATE INDEX WSTRATE_HBS_SPC_FK_I ON WASTE_RESIDUE_RATE (SCALE_PRODUCT_CODE);
CREATE INDEX WSTRATE_HBS_SSC_FK_I ON WASTE_RESIDUE_RATE (SCALE_SPECIES_CODE);

-- Foreign Keys (commented for later use)
