-- DDL Migration for WASTE_REPORTING_UNIT (DBeaver style)
-- Table columns
CREATE TABLE WASTE_REPORTING_UNIT (
    CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
    CLIENT_NUMBER VARCHAR2(8) NOT NULL,
    WASTE_SAMPLING_OPTION_CODE VARCHAR2(3) NOT NULL,
    WASTE_DISPERSED_CV_CODE VARCHAR2(3),
    WASTE_ACCUMULATED_CV_CODE VARCHAR2(3),
    APPRAISAL_METHOD_CODE VARCHAR2(1),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    REPORTING_UNIT_ID NUMBER(12,0) NOT NULL,
    ORG_UNIT_NO NUMBER(10,0) NOT NULL
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016434 CHECK (ORG_UNIT_NO IS NOT NULL);
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016435 CHECK (CLIENT_LOCN_CODE IS NOT NULL);
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016436 CHECK (CLIENT_NUMBER IS NOT NULL);
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016437 CHECK (WASTE_SAMPLING_OPTION_CODE IS NOT NULL);
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016439 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016441 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016443 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016445 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016447 CHECK (UPDATE_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT SYS_C0016433 CHECK (REPORTING_UNIT_ID IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_REPORTING_UNIT ADD CONSTRAINT WRU_PK PRIMARY KEY (REPORTING_UNIT_ID);

-- Indexes
CREATE INDEX WRU_WDCV_FK_I ON WASTE_REPORTING_UNIT (WASTE_DISPERSED_CV_CODE);
CREATE INDEX WRU_CL_FK_I ON WASTE_REPORTING_UNIT (CLIENT_NUMBER, CLIENT_LOCN_CODE);
CREATE INDEX WRU_OU_FK_I ON WASTE_REPORTING_UNIT (ORG_UNIT_NO);
CREATE INDEX WRU_SOC_FK_I ON WASTE_REPORTING_UNIT (WASTE_SAMPLING_OPTION_CODE);
CREATE INDEX WRU_WACV_FK_I ON WASTE_REPORTING_UNIT (WASTE_ACCUMULATED_CV_CODE);

-- Foreign Keys (commented for later use)

