-- DDL migration for HBS_CRYPTOGRAPHY_METHOD (DBeaver style)
CREATE TABLE HBS_CRYPTOGRAPHY_METHOD (
    HBS_CRYPT_METHOD_ID NUMBER(2,0) NOT NULL,
    DESCRIPTION VARCHAR2(30) NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30),
    UPDATE_TIMESTAMP DATE
);

-- Explicit CHECK constraints
ALTER TABLE HBS_CRYPTOGRAPHY_METHOD ADD CONSTRAINT SYS_C0017918 CHECK (HBS_CRYPT_METHOD_ID IS NOT NULL);
ALTER TABLE HBS_CRYPTOGRAPHY_METHOD ADD CONSTRAINT SYS_C0017919 CHECK (DESCRIPTION IS NOT NULL);
ALTER TABLE HBS_CRYPTOGRAPHY_METHOD ADD CONSTRAINT SYS_C0017920 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE HBS_CRYPTOGRAPHY_METHOD ADD CONSTRAINT SYS_C0017921 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE HBS_CRYPTOGRAPHY_METHOD ADD CONSTRAINT SYS_C0017922 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE HBS_CRYPTOGRAPHY_METHOD ADD CONSTRAINT SYS_C0017923 CHECK (ENTRY_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE HBS_CRYPTOGRAPHY_METHOD ADD CONSTRAINT HBS_CRYPTOGRAPHY_METHOD_PK PRIMARY KEY (HBS_CRYPT_METHOD_ID);

-- Unique Index

-- No foreign keys found
