-- DDL Migration for DTL_SCL_DOC_TRANSMISSION (DBeaver style)
-- Table columns
CREATE TABLE DTL_SCL_DOC_TRANSMISSION (
    HBS_XML_TRANS_STEP_CODE VARCHAR2(3) NOT NULL,
    TRANSMISSION_ID NUMBER(32,0) NOT NULL,
    HBS_PROCESSING_STATUS_CODE VARCHAR2(3) NOT NULL,
    USER_ID VARCHAR2(30),
    CLIENT_LOCN_CODE VARCHAR2(2),
    CLIENT_NUMBER VARCHAR2(8),
    BATCH_COUNT NUMBER(10,0) NOT NULL,
    ACCEPTED_IND VARCHAR2(1) NOT NULL,
    FILE_NAME VARCHAR2(100) NOT NULL,
    FILE_DATETIME DATE NOT NULL,
    RECORD_COUNT NUMBER(10,0) NOT NULL,
    TEST_FILE_IND VARCHAR2(1),
    INPUT_USERID VARCHAR2(30),
    RECD_DIRECTORY VARCHAR2(200),
    RECD_CLIENT_NUMBER VARCHAR2(8),
    HBS_XML_PURGE_STATUS_CODE VARCHAR2(3),
    HBS_XML_PURGE_TIMESTAMP DATE,
    SOFTWARE_PRODUCT VARCHAR2(12),
    SOFTWARE_VERSION VARCHAR2(4),
    SOFTWARE_REVISION VARCHAR2(4),
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30),
    UPDATE_TIMESTAMP DATE
);

-- Explicit CHECK constraints (NOT NULL and other conditions)
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017869 CHECK (HBS_XML_TRANS_STEP_CODE IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017870 CHECK (TRANSMISSION_ID IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017871 CHECK (HBS_PROCESSING_STATUS_CODE IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017872 CHECK (BATCH_COUNT IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017873 CHECK (ACCEPTED_IND IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017874 CHECK (FILE_NAME IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017875 CHECK (FILE_DATETIME IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017876 CHECK (RECORD_COUNT IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017877 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0017878 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0038927 CHECK (ACCEPTED_IND IN ('Y', 'N'));
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT SYS_C0038928 CHECK (TEST_FILE_IND IN ('Y', 'N'));

-- Primary Key
ALTER TABLE DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT DTLDOCTRAN_PK PRIMARY KEY (TRANSMISSION_ID);

-- Indexes
CREATE INDEX DTLDOCTRAN_MOF_CL_FK_I ON DTL_SCL_DOC_TRANSMISSION (CLIENT_NUMBER, CLIENT_LOCN_CODE);

-- Foreign Keys (commented for later use)
