-- DDL Migration for WASTE_HISTORY (DBeaver style)
-- Table columns
CREATE TABLE WASTE_HISTORY (
    WASTE_HISTORY_ID NUMBER(12,0) NOT NULL,
    WASTE_ASSESSMENT_AREA_ID NUMBER(12,0) NOT NULL,
    VERSION_ID NUMBER(12,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints (NOT NULL)
ALTER TABLE WASTE_HISTORY ADD CONSTRAINT SYS_C0020649 CHECK (WASTE_HISTORY_ID IS NOT NULL);
ALTER TABLE WASTE_HISTORY ADD CONSTRAINT SYS_C0020650 CHECK (WASTE_ASSESSMENT_AREA_ID IS NOT NULL);
ALTER TABLE WASTE_HISTORY ADD CONSTRAINT SYS_C0020651 CHECK (VERSION_ID IS NOT NULL);
ALTER TABLE WASTE_HISTORY ADD CONSTRAINT SYS_C0020652 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_HISTORY ADD CONSTRAINT SYS_C0020653 CHECK (ENTRY_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_HISTORY ADD CONSTRAINT WH_PK PRIMARY KEY (WASTE_HISTORY_ID);

-- Unique Index
CREATE UNIQUE INDEX WH_UK ON WASTE_HISTORY (WASTE_ASSESSMENT_AREA_ID, VERSION_ID);

-- Foreign Keys (commented for later use)
