-- Migration for THE.WASTE_TYPE_CODE

CREATE TABLE THE.WASTE_TYPE_CODE (
    WASTE_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WATC_PK PRIMARY KEY (WASTE_TYPE_CODE),
    CONSTRAINT WATC_C1 CHECK (WASTE_TYPE_CODE IS NOT NULL),
    CONSTRAINT WATC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WATC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WATC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WATC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
