-- Migration for THE.WASTE_HARVEST_METHOD_CODE

CREATE TABLE THE.WASTE_HARVEST_METHOD_CODE (
    WASTE_HARVEST_METHOD_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WHMC_PK PRIMARY KEY (WASTE_HARVEST_METHOD_CODE),
    CONSTRAINT WHMC_C1 CHECK (WASTE_HARVEST_METHOD_CODE IS NOT NULL),
    CONSTRAINT WHMC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WHMC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WHMC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WHMC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- No foreign key constraints found for this table.
