-- DDL migration for THE.COAST_SCALE_GRADE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE COAST_SCALE_GRADE_CODE (
    COAST_SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0028314 CHECK (COAST_SCALE_GRADE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0028315 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0028316 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0028318 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0028320 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE COAST_SCALE_GRADE_CODE ADD CONSTRAINT CSGC_PK PRIMARY KEY (COAST_SCALE_GRADE_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
