-- Migration for THE.WASTE_SAMPLING_OPTION_CODE

CREATE TABLE THE.WASTE_SAMPLING_OPTION_CODE (
    WASTE_SAMPLING_OPTION_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WSOC_PK PRIMARY KEY (WASTE_SAMPLING_OPTION_CODE),
    CONSTRAINT WSOC_C1 CHECK (WASTE_SAMPLING_OPTION_CODE IS NOT NULL),
    CONSTRAINT WSOC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WSOC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WSOC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WSOC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
