-- Migration for THE.WASTE_COMMENT_CODE

CREATE TABLE THE.WASTE_COMMENT_CODE (
    WASTE_COMMENT_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WACC_PK PRIMARY KEY (WASTE_COMMENT_CODE),
    CONSTRAINT WACC_C1 CHECK (WASTE_COMMENT_CODE IS NOT NULL),
    CONSTRAINT WACC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WACC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WACC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WACC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
