-- DDL migration for THE.SCALE_PRODUCT_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE SCALE_PRODUCT_CODE (
    SCALE_PRODUCT_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0029716 CHECK (SCALE_PRODUCT_CODE IS NOT NULL),
    CONSTRAINT SYS_C0029718 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0029721 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029724 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029727 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE SCALE_PRODUCT_CODE ADD CONSTRAINT SYS_C0034829 PRIMARY KEY (SCALE_PRODUCT_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
