-- DDL migration for THE.MIME_TYPE_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE MIME_TYPE_CODE (
    MIME_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0029748 CHECK (MIME_TYPE_CODE IS NOT NULL),
    CONSTRAINT SYS_C0029749 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0029750 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029751 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029752 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE MIME_TYPE_CODE ADD CONSTRAINT SYS_C0034825 PRIMARY KEY (MIME_TYPE_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
