-- Migration for THE.WASTE_PLOT_SIZE_CODE

CREATE TABLE THE.WASTE_PLOT_SIZE_CODE (
    WASTE_PLOT_SIZE_CODE NUMBER(22) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT PSC_PK PRIMARY KEY (WASTE_PLOT_SIZE_CODE),
    CONSTRAINT PSC_C1 CHECK (WASTE_PLOT_SIZE_CODE IS NOT NULL),
    CONSTRAINT PSC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT PSC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT PSC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT PSC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
