-- Migration for THE.WASTE_ASSESS_AREA_STS_CODE

CREATE TABLE THE.WASTE_ASSESS_AREA_STS_CODE (
    WASTE_ASSESS_AREA_STS_CODE VARCHAR2(4) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WAASC_PK PRIMARY KEY (WASTE_ASSESS_AREA_STS_CODE),
    CONSTRAINT WAASC_C1 CHECK (WASTE_ASSESS_AREA_STS_CODE IS NOT NULL),
    CONSTRAINT WAASC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WAASC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WAASC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WAASC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
