-- Migration for THE.WASTE_MATERIAL_KIND_CODE

CREATE TABLE THE.WASTE_MATERIAL_KIND_CODE (
    WASTE_MATERIAL_KIND_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WMKC_PK PRIMARY KEY (WASTE_MATERIAL_KIND_CODE),
    CONSTRAINT WMKC_C1 CHECK (WASTE_MATERIAL_KIND_CODE IS NOT NULL),
    CONSTRAINT WMKC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WMKC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WMKC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WMKC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
