-- Migration for THE.WASTE_LEVEL_CODE

CREATE TABLE THE.WASTE_LEVEL_CODE (
    WASTE_LEVEL_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WLC_PK PRIMARY KEY (WASTE_LEVEL_CODE),
    CONSTRAINT WLC_C1 CHECK (WASTE_LEVEL_CODE IS NOT NULL),
    CONSTRAINT WLC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WLC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WLC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WLC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
