-- Migration for THE.WASTE_DECAY_TYPE_CODE

CREATE TABLE THE.WASTE_DECAY_TYPE_CODE (
    WASTE_DECAY_TYPE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT DTC_PK PRIMARY KEY (WASTE_DECAY_TYPE_CODE),
    CONSTRAINT DTC_C1 CHECK (WASTE_DECAY_TYPE_CODE IS NOT NULL),
    CONSTRAINT DTC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT DTC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT DTC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT DTC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
