-- DDL migration for DATA_SOURCE_CODE (DBeaver style)
CREATE TABLE DATA_SOURCE_CODE (
    DATA_SOURCE_CODE VARCHAR2(10) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015735 CHECK (DATA_SOURCE_CODE IS NOT NULL);
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015737 CHECK (DESCRIPTION IS NOT NULL);
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015739 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015740 CHECK (EXPIRY_DATE IS NOT NULL);
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT SYS_C0015742 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE DATA_SOURCE_CODE ADD CONSTRAINT DSC_PK PRIMARY KEY (DATA_SOURCE_CODE);

-- Unique Index

-- No foreign keys found
