-- DDL migration for THE.SCALE_SPECIES_CODE
-- Generated on 2025-08-15
-- Format: DBeaver style, explicit constraints

CREATE TABLE SCALE_SPECIES_CODE (
    SCALE_SPECIES_CODE VARCHAR2(2) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT SYS_C0029653 CHECK (SCALE_SPECIES_CODE IS NOT NULL),
    CONSTRAINT SYS_C0029654 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT SYS_C0029655 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029656 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT SYS_C0029657 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- Primary Key
ALTER TABLE SCALE_SPECIES_CODE ADD CONSTRAINT SYS_C0034838 PRIMARY KEY (SCALE_SPECIES_CODE);

-- Unique Index (created by PK)

-- No foreign keys found
