-- Migration for THE.WASTE_BORDERLINE_CODE

CREATE TABLE THE.WASTE_BORDERLINE_CODE (
    WASTE_BORDERLINE_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT BC_PK PRIMARY KEY (WASTE_BORDERLINE_CODE),
    CONSTRAINT BC_C1 CHECK (WASTE_BORDERLINE_CODE IS NOT NULL),
    CONSTRAINT BC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT BC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT BC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT BC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
