-- Migration for THE.WASTE_ASSESSMENT_METHOD_CODE

CREATE TABLE THE.WASTE_ASSESSMENT_METHOD_CODE (
    WASTE_ASSESSMENT_METHOD_CODE VARCHAR2(4) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WAMC_PK PRIMARY KEY (WASTE_ASSESSMENT_METHOD_CODE),
    CONSTRAINT WAMC_C1 CHECK (WASTE_ASSESSMENT_METHOD_CODE IS NOT NULL),
    CONSTRAINT WAMC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WAMC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WAMC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WAMC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);


-- No foreign key constraints found for this table.
