-- Migration for THE.WASTE_PIECE_END_CODE

CREATE TABLE THE.WASTE_PIECE_END_CODE (
    WASTE_PIECE_END_CODE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT PEC_PK PRIMARY KEY (WASTE_PIECE_END_CODE),
    CONSTRAINT PEC_C1 CHECK (WASTE_PIECE_END_CODE IS NOT NULL),
    CONSTRAINT PEC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT PEC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT PEC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT PEC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- No foreign key constraints found for this table.
