-- Migration for THE.WASTE_STRATUM_TYPE_CODE

CREATE TABLE THE.WASTE_STRATUM_TYPE_CODE (
    WASTE_STRATUM_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(120) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    CONSTRAINT WSTC_PK PRIMARY KEY (WASTE_STRATUM_TYPE_CODE),
    CONSTRAINT WSTC_C1 CHECK (WASTE_STRATUM_TYPE_CODE IS NOT NULL),
    CONSTRAINT WSTC_C2 CHECK (DESCRIPTION IS NOT NULL),
    CONSTRAINT WSTC_C3 CHECK (EFFECTIVE_DATE IS NOT NULL),
    CONSTRAINT WSTC_C4 CHECK (EXPIRY_DATE IS NOT NULL),
    CONSTRAINT WSTC_C5 CHECK (UPDATE_TIMESTAMP IS NOT NULL)
);

-- No foreign key constraints found for this table.
