-- DDL migration for WASTE_STRATUM (DBeaver style)
CREATE TABLE WASTE_STRATUM (
    WASTE_STRATUM_ID NUMBER(12,0) NOT NULL,
    WASTE_ASSESSMENT_AREA_ID NUMBER(12,0) NOT NULL,
    WASTE_STRATUM_TYPE_CODE VARCHAR2(3) NOT NULL,
    WASTE_TYPE_CODE VARCHAR2(3),
    WASTE_HARVEST_METHOD_CODE VARCHAR2(2),
    WASTE_ASSESSMENT_METHOD_CODE VARCHAR2(4) NOT NULL,
    WASTE_PLOT_SIZE_CODE NUMBER(5,0),
    WASTE_LEVEL_CODE VARCHAR2(1),
    STRATUM_AREA NUMBER(5,2) NOT NULL,
    TOTAL_ESTIMATED_VOLUME NUMBER(5,0),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    WASTE_SURVEYOR_LICENCE VARCHAR2(4)
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027884 CHECK (WASTE_STRATUM_ID IS NOT NULL);
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027886 CHECK (WASTE_ASSESSMENT_AREA_ID IS NOT NULL);
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027889 CHECK (WASTE_STRATUM_TYPE_CODE IS NOT NULL);
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027892 CHECK (WASTE_ASSESSMENT_METHOD_CODE IS NOT NULL);
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027895 CHECK (STRATUM_AREA IS NOT NULL);
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027898 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027900 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027902 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027904 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT SYS_C0027906 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT WSTR_PK PRIMARY KEY (WASTE_STRATUM_ID);

-- Unique Index

-- Non-unique Indexes
CREATE INDEX WSTR_PSC_FK_I ON WASTE_STRATUM (WASTE_PLOT_SIZE_CODE);
CREATE INDEX WSTR_WAA_FK_I ON WASTE_STRATUM (WASTE_ASSESSMENT_AREA_ID);
CREATE INDEX WSTR_WAMC_FK_I ON WASTE_STRATUM (WASTE_ASSESSMENT_METHOD_CODE);
CREATE INDEX WSTR_WLC_FK_I ON WASTE_STRATUM (WASTE_LEVEL_CODE);
CREATE INDEX WSTR_WSTC_FK_I ON WASTE_STRATUM (WASTE_STRATUM_TYPE_CODE);
CREATE INDEX WSTR_WTC_FK_I ON WASTE_STRATUM (WASTE_TYPE_CODE);
CREATE INDEX WSTR_HMC_FK_I ON WASTE_STRATUM (WASTE_HARVEST_METHOD_CODE);

-- Foreign keys (to be added separately)