-- DDL migration for PROV_FOREST_USE (DBeaver style)
CREATE TABLE PROV_FOREST_USE (
    FOREST_FILE_ID VARCHAR2(10) NOT NULL,
    FILE_STATUS_ST VARCHAR2(3),
    FILE_STATUS_DATE DATE,
    FILE_TYPE_CODE VARCHAR2(3),
    FOREST_REGION NUMBER(10,0) NOT NULL,
    BCTS_ORG_UNIT NUMBER(10,0),
    SB_FUNDED_IND VARCHAR2(1) DEFAULT 'N' NOT NULL,
    DISTRICT_ADMIN_ZONE VARCHAR2(4),
    MGMT_UNIT_TYPE VARCHAR2(1),
    MGMT_UNIT_ID VARCHAR2(4),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    FOREST_TENURE_GUID RAW(16) DEFAULT SYS_GUID() NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT SYS_C0012190 CHECK (FOREST_FILE_ID IS NOT NULL);
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT SYS_C0012191 CHECK (FOREST_REGION IS NOT NULL);
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT SYS_C0012192 CHECK (SB_FUNDED_IND IS NOT NULL);
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT AVCON_1148331360_SB_FU_001 CHECK (SB_FUNDED_IND IN ('N', 'Y'));
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT SYS_C0012193 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT SYS_C0012194 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT SYS_C0012195 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT SYS_C0012196 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT SYS_C0012197 CHECK (UPDATE_TIMESTAMP IS NOT NULL);
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT SYS_C00111802 CHECK (FOREST_TENURE_GUID IS NOT NULL);

-- Primary Key
ALTER TABLE PROV_FOREST_USE ADD CONSTRAINT PFU_PK PRIMARY KEY (FOREST_FILE_ID);

-- Unique Indexes
CREATE UNIQUE INDEX PFU_GUID_UK ON PROV_FOREST_USE (FOREST_TENURE_GUID);

-- Non-unique Indexes
CREATE INDEX PFU_FSC_FK_I ON PROV_FOREST_USE (FILE_STATUS_ST);
CREATE INDEX PFU_FTCD_FK_I ON PROV_FOREST_USE (FILE_TYPE_CODE);
CREATE INDEX PFU_I2 ON PROV_FOREST_USE (FOREST_REGION);
CREATE INDEX PFU_OU_FK_I ON PROV_FOREST_USE (BCTS_ORG_UNIT);

-- Foreign keys (to be added separately)
