-- DDL migration for MOF_USER_ORG_DEFAULT (DBeaver style)
CREATE TABLE MOF_USER_ORG_DEFAULT (
    APPLICATION_ACRONYM VARCHAR2(30) NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    ORG_UNIT_NO NUMBER(10,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    REVISION_COUNT NUMBER(5,0) NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE MOF_USER_ORG_DEFAULT ADD CONSTRAINT SYS_C0018719 CHECK (APPLICATION_ACRONYM IS NOT NULL);
ALTER TABLE MOF_USER_ORG_DEFAULT ADD CONSTRAINT SYS_C0018720 CHECK (USER_ID IS NOT NULL);
ALTER TABLE MOF_USER_ORG_DEFAULT ADD CONSTRAINT SYS_C0018721 CHECK (ORG_UNIT_NO IS NOT NULL);
ALTER TABLE MOF_USER_ORG_DEFAULT ADD CONSTRAINT SYS_C0018722 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE MOF_USER_ORG_DEFAULT ADD CONSTRAINT SYS_C0018724 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE MOF_USER_ORG_DEFAULT ADD CONSTRAINT SYS_C0018725 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE MOF_USER_ORG_DEFAULT ADD CONSTRAINT SYS_C0018726 CHECK (UPDATE_TIMESTAMP IS NOT NULL);
ALTER TABLE MOF_USER_ORG_DEFAULT ADD CONSTRAINT SYS_C0018727 CHECK (REVISION_COUNT IS NOT NULL);

-- Primary Key
ALTER TABLE MOF_USER_ORG_DEFAULT ADD CONSTRAINT MUOD_PK PRIMARY KEY (APPLICATION_ACRONYM, USER_ID);

-- Unique Index
CREATE UNIQUE INDEX MUOD_UK ON MOF_USER_ORG_DEFAULT (APPLICATION_ACRONYM, USER_ID, ORG_UNIT_NO);

-- No foreign keys found
