-- DDL migration for CUT_BLOCK_OPEN_ADMIN (DBeaver style)
CREATE TABLE CUT_BLOCK_OPEN_ADMIN (
    CUT_BLOCK_OPEN_ADMIN_ID NUMBER(10,0) NOT NULL,
    FOREST_FILE_ID VARCHAR2(10),
    TIMBER_MARK VARCHAR2(10),
    CUT_BLOCK_ID VARCHAR2(10),
    CUTTING_PERMIT_ID VARCHAR2(3),
    DISTURBANCE_GROSS_AREA NUMBER(11,4),
    DISTURBANCE_START_DATE DATE,
    DISTURBANCE_END_DATE DATE,
    OPENING_ID NUMBER(10,0),
    OPENING_GROSS_AREA NUMBER(11,4),
    PLANNED_HARVEST_DATE DATE,
    PLANNED_GROSS_BLOCK_AREA NUMBER(11,4),
    PLANNED_NET_BLOCK_AREA NUMBER(11,4),
    OPENING_PRIME_LICENCE_IND VARCHAR2(1),
    CB_SKEY NUMBER(10,0),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT SYS_C0012316 CHECK (CUT_BLOCK_OPEN_ADMIN_ID IS NOT NULL);
ALTER TABLE CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT SYS_C0012318 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT SYS_C0012320 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT SYS_C0012322 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT SYS_C0012325 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT SYS_C0012328 CHECK (UPDATE_TIMESTAMP IS NOT NULL);
ALTER TABLE CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT AVCON_1054232647_OPENI_000 CHECK (OPENING_PRIME_LICENCE_IND IN ('N', 'Y'));

-- Primary Key
ALTER TABLE CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT CBOA_PK PRIMARY KEY (CUT_BLOCK_OPEN_ADMIN_ID);

-- Indexes
CREATE INDEX CBOA_CBLK_FK_I ON CUT_BLOCK_OPEN_ADMIN (CUT_BLOCK_ID);
CREATE INDEX CBOA_CBSKEY_I ON CUT_BLOCK_OPEN_ADMIN (CB_SKEY);
CREATE INDEX CBOA_FFID_MARK_BLK_I ON CUT_BLOCK_OPEN_ADMIN (FOREST_FILE_ID, TIMBER_MARK, CUT_BLOCK_ID);
CREATE INDEX CBOA_MARK_BLK_I ON CUT_BLOCK_OPEN_ADMIN (TIMBER_MARK, CUT_BLOCK_ID);
CREATE INDEX CBOA_O_FK_I ON CUT_BLOCK_OPEN_ADMIN (OPENING_ID);

-- Foreign keys (to be added separately)