-- DDL migration for WASTE_BILLING_XREF (DBeaver style)
CREATE TABLE WASTE_BILLING_XREF (
    CATASTROPHIC_IND VARCHAR2(1) NOT NULL,
    SCALE_GRADE_CODE VARCHAR2(1) NOT NULL,
    WASTE_MATERIAL_KIND_CODE VARCHAR2(1) NOT NULL,
    WASTE_CLASS_CODE VARCHAR2(1) NOT NULL,
    WASTE_MATERIAL_CLASS_CODE VARCHAR2(1),
    BILLING_IND VARCHAR2(1) NOT NULL,
    CUT_CONTROL_IND VARCHAR2(1) NOT NULL,
    OTHER_IND VARCHAR2(1) NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT SYS_C0027847 CHECK (CATASTROPHIC_IND IS NOT NULL);
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT SYS_C0027848 CHECK (SCALE_GRADE_CODE IS NOT NULL);
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT SYS_C0027849 CHECK (WASTE_MATERIAL_KIND_CODE IS NOT NULL);
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT SYS_C0027850 CHECK (WASTE_CLASS_CODE IS NOT NULL);
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT SYS_C0027851 CHECK (BILLING_IND IS NOT NULL);
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT SYS_C0027852 CHECK (CUT_CONTROL_IND IS NOT NULL);
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT SYS_C0027854 CHECK (OTHER_IND IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT WBX_PK PRIMARY KEY (CATASTROPHIC_IND, SCALE_GRADE_CODE, WASTE_MATERIAL_KIND_CODE, WASTE_CLASS_CODE);

-- Unique Index

-- Non-unique Indexes
CREATE INDEX WBX_WMCC_FK_I ON WASTE_BILLING_XREF (WASTE_MATERIAL_CLASS_CODE);
CREATE INDEX WBX_WMKC_FK_I ON WASTE_BILLING_XREF (WASTE_MATERIAL_KIND_CODE);
CREATE INDEX WBX_SGC_FK_I ON WASTE_BILLING_XREF (SCALE_GRADE_CODE);
CREATE INDEX WBX_WCC_FK_I ON WASTE_BILLING_XREF (WASTE_CLASS_CODE);

-- Foreign keys (to be added separately)
