-- DDL migration for WASTE_ASSESSMENT_SURVEY_MAP (DBeaver style)
CREATE TABLE WASTE_ASSESSMENT_SURVEY_MAP (
    WASTE_ASSESSMENT_AREA_ID NUMBER(12,0) NOT NULL,
    SURVEY_MAP_DOCUMENT BLOB,
    WASTE_ASSESSMENT_SURVEY_MAP_ID NUMBER(12,0) NOT NULL,
    SURVEY_MAP_DOCUMENT_NAME VARCHAR2(50) NOT NULL,
    SURVEY_MAP_MIME_TYPE_CODE VARCHAR2(3),
    WASTE_ASSESS_AREA_STS_CODE VARCHAR2(4) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_ASSESSMENT_SURVEY_MAP ADD CONSTRAINT SYS_C00326671 CHECK (WASTE_ASSESSMENT_SURVEY_MAP_ID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SURVEY_MAP ADD CONSTRAINT SYS_C00326672 CHECK (SURVEY_MAP_DOCUMENT_NAME IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SURVEY_MAP ADD CONSTRAINT SYS_C00326673 CHECK (WASTE_ASSESS_AREA_STS_CODE IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SURVEY_MAP ADD CONSTRAINT SYS_C00326674 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SURVEY_MAP ADD CONSTRAINT SYS_C00326675 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_ASSESSMENT_SURVEY_MAP ADD CONSTRAINT SYS_C0033000 CHECK (WASTE_ASSESSMENT_AREA_ID IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_ASSESSMENT_SURVEY_MAP ADD CONSTRAINT WAM_PK PRIMARY KEY (WASTE_ASSESSMENT_SURVEY_MAP_ID);

-- Unique Index

-- Non-unique Indexes
CREATE INDEX WAM_WAA_FK_I ON WASTE_ASSESSMENT_SURVEY_MAP (WASTE_ASSESSMENT_AREA_ID);

-- Foreign keys (to be added separately)