-- DDL migration for WASTE_PLOT (DBeaver style)
CREATE TABLE WASTE_PLOT (
    WASTE_PLOT_ID NUMBER(12,0) NOT NULL,
    WASTE_STRATUM_ID NUMBER(12,0) NOT NULL,
    WASTE_PLOT_NUMBER NUMBER(3,0) NOT NULL,
    WASTE_BASELINE VARCHAR2(1),
    WASTE_STRIP NUMBER(2,0),
    MEASURE_FACTOR NUMBER(3,0) NOT NULL,
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    WASTE_SURVEYOR_LICENCE VARCHAR2(4)
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_PLOT ADD CONSTRAINT SYS_C0027916 CHECK (WASTE_PLOT_ID IS NOT NULL);
ALTER TABLE WASTE_PLOT ADD CONSTRAINT SYS_C0027918 CHECK (WASTE_STRATUM_ID IS NOT NULL);
ALTER TABLE WASTE_PLOT ADD CONSTRAINT SYS_C0027920 CHECK (WASTE_PLOT_NUMBER IS NOT NULL);
ALTER TABLE WASTE_PLOT ADD CONSTRAINT SYS_C0027922 CHECK (MEASURE_FACTOR IS NOT NULL);
ALTER TABLE WASTE_PLOT ADD CONSTRAINT SYS_C0027924 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_PLOT ADD CONSTRAINT SYS_C0027926 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_PLOT ADD CONSTRAINT SYS_C0027928 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_PLOT ADD CONSTRAINT SYS_C0027929 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_PLOT ADD CONSTRAINT SYS_C0027931 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_PLOT ADD CONSTRAINT WPLO_PK PRIMARY KEY (WASTE_PLOT_ID);

-- Unique Indexes
CREATE UNIQUE INDEX WPLO_UK ON WASTE_PLOT (WASTE_STRATUM_ID, WASTE_PLOT_NUMBER);

-- Non-unique Indexes
CREATE INDEX WPLO_WSTR_FK_I ON WASTE_PLOT (WASTE_STRATUM_ID);

-- Foreign keys (to be added separately)
