-- DDL migration for OPENING (DBeaver style)
CREATE TABLE OPENING (
    OPENING_ID NUMBER(10,0) NOT NULL,
    GEO_DISTRICT_NO NUMBER(10,0) NOT NULL,
    ADMIN_DISTRICT_NO NUMBER(10,0) NOT NULL,
    MAPSHEET_GRID VARCHAR2(3),
    MAPSHEET_LETTER VARCHAR2(1),
    MAPSHEET_SQUARE VARCHAR2(3),
    MAPSHEET_QUAD VARCHAR2(1),
    MAPSHEET_SUB_QUAD VARCHAR2(1),
    OPENING_NUMBER VARCHAR2(4),
    OPENING_LOCN_NAME VARCHAR2(30),
    OPEN_CATEGORY_CODE VARCHAR2(7) NOT NULL,
    LICENSEE_OPENING_ID VARCHAR2(30),
    TSB_NUMBER_CODE VARCHAR2(3),
    OPENING_STATUS_CODE VARCHAR2(3) NOT NULL,
    ORG_UNIT_NO NUMBER(10,0),
    DIST_ADMIN_ZONE VARCHAR2(2),
    MAX_ALLOW_PERMNT_ACCESS_PCT NUMBER(3,1),
    PREV_AGE_CLASS_CODE VARCHAR2(1),
    PREV_SITE_INDEX NUMBER(5,0),
    PREV_SITE_INDEX_SOURCE_CODE VARCHAR2(1),
    PREV_HEIGHT_CLASS_CODE VARCHAR2(1),
    PREV_SITE_CLASS_CODE VARCHAR2(1),
    PREV_STOCKING_CLASS_CODE VARCHAR2(1),
    PREV_STOCKING_STATUS_CODE VARCHAR2(3),
    PREV_TREE_SPP1_CODE VARCHAR2(8),
    PREV_TREE_SPP2_CODE VARCHAR2(8),
    APP_ENT_BY_USERID VARCHAR2(30),
    APPROVE_DATE DATE,
    AMENDMENT_IND VARCHAR2(1),
    RESULTS_SUBMISSION_ID NUMBER(10,0),
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    REVISION_COUNT NUMBER(5,0) NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009157 CHECK (OPENING_ID IS NOT NULL);
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009158 CHECK (GEO_DISTRICT_NO IS NOT NULL);
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009160 CHECK (ADMIN_DISTRICT_NO IS NOT NULL);
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009162 CHECK (OPEN_CATEGORY_CODE IS NOT NULL);
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009164 CHECK (OPENING_STATUS_CODE IS NOT NULL);
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009166 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009168 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009170 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009172 CHECK (UPDATE_TIMESTAMP IS NOT NULL);
ALTER TABLE OPENING ADD CONSTRAINT O_C_SYS_C009174 CHECK (REVISION_COUNT IS NOT NULL);

-- Primary Key
ALTER TABLE OPENING ADD CONSTRAINT O_PK PRIMARY KEY (OPENING_ID);

-- Unique Index

-- Non-unique Indexes
CREATE INDEX O_LICENSEE_ID_I ON OPENING (LICENSEE_OPENING_ID);
CREATE INDEX O_OPENING_NUMBER_I ON OPENING (OPENING_NUMBER);
CREATE INDEX O_OPEN_CATEGORY_CODE_I ON OPENING (OPEN_CATEGORY_CODE);
CREATE INDEX O_OU_FK_I ON OPENING (ADMIN_DISTRICT_NO);
CREATE INDEX O_STATUS_I ON OPENING (OPENING_STATUS_CODE);

-- Foreign keys (to be added separately)
