-- DDL migration for PIECE_SCALE_SUMMARY (DBeaver style)
CREATE TABLE PIECE_SCALE_SUMMARY (
    DOCUMENT_CONTROL_NUMBER NUMBER(10,0) NOT NULL,
    VERSION NUMBER(10,0) NOT NULL,
    PSSMRY_TYPE VARCHAR2(10) NOT NULL,
    LICENSE_NUMBER VARCHAR2(4),
    QUANT_LIC_TYPE_CD VARCHAR2(1),
    RETURN_NUMBER VARCHAR2(4),
    SCALE_SITE_ID_NMBR VARCHAR2(4) NOT NULL,
    SCALE_DATE DATE NOT NULL,
    TIMBER_MARK VARCHAR2(6),
    LOG_COUNT NUMBER(6,0) NOT NULL,
    CLIENT_NUMBER_PAID_BY VARCHAR2(8),
    CLIENT_LOCN_CODE_PAID_BY VARCHAR2(2),
    CLIENT_NUMBER_COPIED_TO VARCHAR2(8),
    CLIENT_LOCN_CODE_COPIED_TO VARCHAR2(2),
    SCL_RTN_VERSION_STATE_CODE VARCHAR2(3) NOT NULL,
    SCL_RTN_CATEGORY_CODE VARCHAR2(2) NOT NULL,
    INPUT_TIMBER_MARK VARCHAR2(6),
    INPUT_SCALER_LICENSE_NUM VARCHAR2(4),
    ACTIVE_VERSION_IND VARCHAR2(1) NOT NULL,
    QUEUED_FOR_PRINT_IND VARCHAR2(1) NOT NULL,
    VISIBILITY_IND VARCHAR2(1) NOT NULL,
    PLACE_OF_SCALE VARCHAR2(40),
    PENDING_TXN_COMMENT VARCHAR2(240),
    NUMBER_OF_CHAINS VARCHAR2(14),
    CAMP_BOOM_NUMBER VARCHAR2(18),
    AREA_CUT NUMBER(7,1),
    NUMBER_OF_SECTIONS NUMBER(3,1),
    PERIOD_START_DATE DATE,
    FIELD_SCALE_DECK_ID VARCHAR2(1),
    CUT_BLOCK_ID VARCHAR2(10),
    VERSION_COMMENT VARCHAR2(240),
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30),
    UPDATE_TIMESTAMP DATE
);

-- Explicit CHECK constraints
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024261 CHECK (DOCUMENT_CONTROL_NUMBER IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024262 CHECK (VERSION IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024263 CHECK (PSSMRY_TYPE IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024264 CHECK (SCALE_SITE_ID_NMBR IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024265 CHECK (SCALE_DATE IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024266 CHECK (LOG_COUNT IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024267 CHECK (SCL_RTN_VERSION_STATE_CODE IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024268 CHECK (SCL_RTN_CATEGORY_CODE IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024269 CHECK (ACTIVE_VERSION_IND IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024270 CHECK (QUEUED_FOR_PRINT_IND IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024271 CHECK (VISIBILITY_IND IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024272 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT SYS_C0024273 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT AVCON_1025734613_ACTIV_002 CHECK (ACTIVE_VERSION_IND IN ('Y', 'N'));
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT AVCON_1025734613_QUEUE_002 CHECK (QUEUED_FOR_PRINT_IND IN ('Y', 'N'));
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT AVCON_1025734613_VISIB_002 CHECK (VISIBILITY_IND IN ('Y', 'N'));

-- Primary Key
ALTER TABLE PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_PK PRIMARY KEY (DOCUMENT_CONTROL_NUMBER, VERSION);

-- Unique Index

-- Non-unique Indexes
CREATE INDEX PSSMRY_SRCATCD_FK_I ON PIECE_SCALE_SUMMARY (SCL_RTN_CATEGORY_CODE);
CREATE INDEX PSSMRY_SRVERSTATE_FK_I ON PIECE_SCALE_SUMMARY (ACTIVE_VERSION_IND);
CREATE INDEX I2$_PIECE_SCALE_SUMMARY ON PIECE_SCALE_SUMMARY (DOCUMENT_CONTROL_NUMBER);
CREATE INDEX PSSMRY_HBSSR_FK_I ON PIECE_SCALE_SUMMARY (SCALE_SITE_ID_NMBR);
CREATE INDEX PSSMRY_MOF_CL_COPIED_TO_FK_I ON PIECE_SCALE_SUMMARY (CLIENT_NUMBER_COPIED_TO);
CREATE INDEX PSSMRY_MOF_CL_FK_I ON PIECE_SCALE_SUMMARY (CLIENT_NUMBER_PAID_BY);
CREATE INDEX PSSMRY_MOF_QL_FK_I ON PIECE_SCALE_SUMMARY (QUANT_LIC_TYPE_CD);
CREATE INDEX PSSMRY_MOF_TM_FK_I ON PIECE_SCALE_SUMMARY (TIMBER_MARK);

-- Foreign keys (to be added separately)
