-- DDL migration for HAULING_AUTHORITY (DBeaver style)
CREATE TABLE HAULING_AUTHORITY (
    TIMBER_MARK VARCHAR2(6) NOT NULL,
    FOREST_FILE_ID VARCHAR2(10),
    MARKING_METHOD_CODE VARCHAR2(1),
    MARKING_INSTRUMENT_CODE VARCHAR2(1),
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    HAULING_AUTHORITY_GUID RAW(16) DEFAULT SYS_GUID() NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE HAULING_AUTHORITY ADD CONSTRAINT SYS_C0012855 CHECK (TIMBER_MARK IS NOT NULL);
ALTER TABLE HAULING_AUTHORITY ADD CONSTRAINT SYS_C0012856 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE HAULING_AUTHORITY ADD CONSTRAINT SYS_C0012857 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE HAULING_AUTHORITY ADD CONSTRAINT SYS_C0012858 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE HAULING_AUTHORITY ADD CONSTRAINT SYS_C0012859 CHECK (UPDATE_TIMESTAMP IS NOT NULL);
ALTER TABLE HAULING_AUTHORITY ADD CONSTRAINT SYS_C0012860 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE HAULING_AUTHORITY ADD CONSTRAINT SYS_C00111798 CHECK (HAULING_AUTHORITY_GUID IS NOT NULL);

-- Primary Key
ALTER TABLE HAULING_AUTHORITY ADD CONSTRAINT HAA_PK PRIMARY KEY (TIMBER_MARK);

-- Unique Indexes
CREATE UNIQUE INDEX HAA_GUID_UK ON HAULING_AUTHORITY (HAULING_AUTHORITY_GUID);

-- Non-unique Indexes
CREATE INDEX HAA_MICD_FK_I ON HAULING_AUTHORITY (MARKING_INSTRUMENT_CODE);
CREATE INDEX HAA_FF_I ON HAULING_AUTHORITY (FOREST_FILE_ID);
CREATE INDEX HAA_MMCD_FK_I ON HAULING_AUTHORITY (MARKING_METHOD_CODE);

-- Foreign keys (to be added separately)
