-- DDL migration for WASTE_T_DISTRIBUTION (DBeaver style)
CREATE TABLE WASTE_T_DISTRIBUTION (
    DEGREES_OF_FREEDOM NUMBER(5,0) NOT NULL,
    CONFIDENCE_INTERVAL NUMBER(8,3) NOT NULL,
    REVISION_COUNT NUMBER(5,0) NOT NULL,
    ENTRY_USERID VARCHAR2(30) NOT NULL,
    ENTRY_TIMESTAMP DATE NOT NULL,
    UPDATE_USERID VARCHAR2(30) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL
);

-- Explicit CHECK constraints
ALTER TABLE WASTE_T_DISTRIBUTION ADD CONSTRAINT SYS_C0027863 CHECK (DEGREES_OF_FREEDOM IS NOT NULL);
ALTER TABLE WASTE_T_DISTRIBUTION ADD CONSTRAINT SYS_C0027864 CHECK (CONFIDENCE_INTERVAL IS NOT NULL);
ALTER TABLE WASTE_T_DISTRIBUTION ADD CONSTRAINT SYS_C0027865 CHECK (REVISION_COUNT IS NOT NULL);
ALTER TABLE WASTE_T_DISTRIBUTION ADD CONSTRAINT SYS_C0027866 CHECK (ENTRY_USERID IS NOT NULL);
ALTER TABLE WASTE_T_DISTRIBUTION ADD CONSTRAINT SYS_C0027867 CHECK (ENTRY_TIMESTAMP IS NOT NULL);
ALTER TABLE WASTE_T_DISTRIBUTION ADD CONSTRAINT SYS_C0027869 CHECK (UPDATE_USERID IS NOT NULL);
ALTER TABLE WASTE_T_DISTRIBUTION ADD CONSTRAINT SYS_C0027871 CHECK (UPDATE_TIMESTAMP IS NOT NULL);

-- Primary Key
ALTER TABLE WASTE_T_DISTRIBUTION ADD CONSTRAINT WTD_PK PRIMARY KEY (DEGREES_OF_FREEDOM);

-- Unique Index

-- No foreign keys found
