-- Foreign key relationships extracted from migration files
-- Generated on 2025-08-15

-- V1.3.17__base_table_WASTE_TYPE_STRATUM_XREF.sql
ALTER TABLE WASTE_TYPE_STRATUM_XREF ADD CONSTRAINT WTSX_WSTC_FK FOREIGN KEY (WASTE_STRATUM_TYPE_CODE) REFERENCES WASTE_STRATUM_TYPE_CODE;
ALTER TABLE WASTE_TYPE_STRATUM_XREF ADD CONSTRAINT WTSX_WTC_FK FOREIGN KEY (WASTE_TYPE_CODE) REFERENCES WASTE_TYPE_CODE;

-- V1.3.15__base_table_WASTE_STRATUM.sql
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT WSTR_WAA_FK FOREIGN KEY (WASTE_ASSESSMENT_AREA_ID) REFERENCES WASTE_ASSESSMENT_AREA;
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT WSTR_PSC_FK FOREIGN KEY (WASTE_PLOT_SIZE_CODE) REFERENCES WASTE_PLOT_SIZE_CODE;
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT WSTR_WAMC_FK FOREIGN KEY (WASTE_ASSESSMENT_METHOD_CODE) REFERENCES WASTE_ASSESSMENT_METHOD_CODE;
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT WSTR_WHMC_FK FOREIGN KEY (WASTE_HARVEST_METHOD_CODE) REFERENCES WASTE_HARVEST_METHOD_CODE;
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT WSTR_WLC_FK FOREIGN KEY (WASTE_LEVEL_CODE) REFERENCES WASTE_LEVEL_CODE;
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT WSTR_WSTC_FK FOREIGN KEY (WASTE_STRATUM_TYPE_CODE) REFERENCES WASTE_STRATUM_TYPE_CODE;
ALTER TABLE WASTE_STRATUM ADD CONSTRAINT WSTR_WTC_FK FOREIGN KEY (WASTE_TYPE_CODE) REFERENCES WASTE_TYPE_CODE;

-- V1.3.12__base_table_WASTE_ASSESSMENT_SURVEY_MAP.sql
ALTER TABLE WASTE_ASSESSMENT_SURVEY_MAP ADD CONSTRAINT WAM_WAASC_FK FOREIGN KEY (WASTE_ASSESS_AREA_STS_CODE) REFERENCES WASTE_ASSESS_AREA_STS_CODE;
ALTER TABLE WASTE_ASSESSMENT_SURVEY_MAP ADD CONSTRAINT WAM_WAA_FK FOREIGN KEY (WASTE_ASSESSMENT_AREA_ID) REFERENCES WASTE_ASSESSMENT_AREA;

-- V1.3.11__base_table_WASTE_ASSESSMENT_AREA.sql (Stopped)
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_CBLK_FK FOREIGN KEY (CB_SKEY) REFERENCES THE.CUT_BLOCK(CB_SKEY);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_HAA_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.HAULING_AUTHORITY(TIMBER_MARK);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_HEEMC_FK FOREIGN KEY (HBS_EDIT_ERR_MESSAGE_CODE,HBS_EDIT_ERR_CATEGORY_CODE) REFERENCES THE.HBS_EDIT_ERR_MESSAGE_CODE(HBS_EDIT_ERR_MESSAGE_CODE,HBS_EDIT_ERR_CATEGORY_CODE);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_MTC2_FK FOREIGN KEY (SURVEY_MAP_MIME_TYPE_CODE) REFERENCES THE.MIME_TYPE_CODE(MIME_TYPE_CODE);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_MTC_FK FOREIGN KEY (WASTE_MATURITY_TYPE_CODE) REFERENCES THE.WASTE_MATURITY_TYPE_CODE(WASTE_MATURITY_TYPE_CODE);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_PFU_FK FOREIGN KEY (FOREST_FILE_ID) REFERENCES THE.PROV_FOREST_USE(FOREST_FILE_ID);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_SITC_FK FOREIGN KEY (WASTE_SITE_TYPE_CODE) REFERENCES THE.WASTE_SITE_TYPE_CODE(WASTE_SITE_TYPE_CODE);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_WAA_FK FOREIGN KEY (PARENT_WAA_ID) REFERENCES THE.WASTE_ASSESSMENT_AREA(WASTE_ASSESSMENT_AREA_ID);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_WARRC_FK FOREIGN KEY (WASTE_AREA_RISK_RATING_CODE) REFERENCES THE.WASTE_AREA_RISK_RATING_CODE(WASTE_AREA_RISK_RATING_CODE);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_WCTC_FK FOREIGN KEY (WASTE_CONDITION_TYPE_CODE) REFERENCES THE.WASTE_CONDITION_TYPE_CODE(WASTE_CONDITION_TYPE_CODE);
--ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_WFRZR_FK FOREIGN KEY (WASTE_FIBRE_RECOVERY_ZONE_RATE) REFERENCES <?>();
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_WPBTC_FK FOREIGN KEY (WASTE_PARENT_BLOCK_TYPE_CODE) REFERENCES THE.WASTE_PARENT_BLOCK_TYPE_CODE(WASTE_PARENT_BLOCK_TYPE_CODE);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_WRU_FK FOREIGN KEY (REPORTING_UNIT_ID) REFERENCES THE.WASTE_REPORTING_UNIT(REPORTING_UNIT_ID);
ALTER TABLE THE.WASTE_ASSESSMENT_AREA ADD CONSTRAINT WAA_WSCC_FK FOREIGN KEY (WASTE_SURVEY_CHECK_CODE) REFERENCES THE.WASTE_SURVEY_CHECK_CODE(WASTE_SURVEY_CHECK_CODE);

-- V1.3.10__base_table_SPECIAL_FOREST_PRODUCT_TALLY.sql (Verify)
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_BATDOC_FK FOREIGN KEY (BATDOC_ID) REFERENCES <?>();
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_DTLSCLDOC_FK FOREIGN KEY (DETAIL_DOCUMENT_NUMBER) REFERENCES <?>();
ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_HCM_FK FOREIGN KEY (HBS_CRYPT_METHOD_ID) REFERENCES THE.HBS_CRYPTOGRAPHY_METHOD(HBS_CRYPT_METHOD_ID);
ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_HEK_FK1 FOREIGN KEY (HBS_ENCR_KEY_ID) REFERENCES THE.HBS_ENCRYPTION_KEY(HBS_ENCR_KEY_ID);
ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_HRPS_FK FOREIGN KEY (HBS_RSA_PADDING_ID) REFERENCES THE.HBS_RSA_PADDING_SCHEME(HBS_RSA_PADDING_ID);
ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_MOF_HATM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.HAULING_AUTHORITY(TIMBER_MARK);
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_MOF_SS_FK FOREIGN KEY (SCALE_SITE_ID_NMBR) REFERENCES <?>();
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_MOF_TM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.TIMBER_MARK(TIMBER_MARK);
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_ORIG_CHK_SCL_SCLR_FK FOREIGN KEY (ORIG_CHK_SCL_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_PRIMARY_SCLR_FK FOREIGN KEY (PRIMARY_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_SECONDARY_SCLR_FK FOREIGN KEY (SECONDARY_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_SETC_FK FOREIGN KEY (SCALE_EVENT_TYPE_CODE) REFERENCES <?>();
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_SFPTYP_FK FOREIGN KEY (HBS_SFP_SCALE_TYPE_CODE) REFERENCES <?>();
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_SIGNING_SCLR_FK FOREIGN KEY (SIGNING_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.SPECIAL_FOREST_PRODUCT_TALLY ADD CONSTRAINT SFPTALLY_SRVERSTATE_FK FOREIGN KEY (SCL_RTN_VERSION_STATE_CODE) REFERENCES <?>();

-- V1.3.4__base_table_LOG_TALLY.sql (Verify)
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_BATDOC_FK FOREIGN KEY (BATDOC_ID) REFERENCES <?>();
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_DTLSCLDOC_FK FOREIGN KEY (DETAIL_DOCUMENT_NUMBER) REFERENCES <?>();
ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_MOF_HATM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.HAULING_AUTHORITY(TIMBER_MARK);
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_MOF_SS_FK FOREIGN KEY (SCALE_SITE_ID_NMBR) REFERENCES <?>();
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_MOF_TM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.TIMBER_MARK(TIMBER_MARK);
ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_ORGDDNDDV_FK FOREIGN KEY (ORIGINAL_DDN,ORIGINAL_DDV) REFERENCES THE.LOG_TALLY(DETAIL_DOCUMENT_NUMBER,VERSION);
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_ORIG_CHK_SCL_SCLR_FK FOREIGN KEY (ORIG_CHK_SCL_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_PRIMARY_SCLR_FK FOREIGN KEY (PRIMARY_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_SECONDARY_SCLR_FK FOREIGN KEY (SECONDARY_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_SETC_FK FOREIGN KEY (SCALE_EVENT_TYPE_CODE) REFERENCES <?>();
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_SIGNING_SCLR_FK FOREIGN KEY (SIGNING_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOGTALLY_VER_STATUS_FK FOREIGN KEY (SCL_RTN_VERSION_STATE_CODE) REFERENCES <?>();
ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOG_TALLY_HCM_FK FOREIGN KEY (HBS_CRYPT_METHOD_ID) REFERENCES THE.HBS_CRYPTOGRAPHY_METHOD(HBS_CRYPT_METHOD_ID);
ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOG_TALLY_HEK_FK1 FOREIGN KEY (HBS_ENCR_KEY_ID) REFERENCES THE.HBS_ENCRYPTION_KEY(HBS_ENCR_KEY_ID);
ALTER TABLE THE.LOG_TALLY ADD CONSTRAINT LOG_TALLY_HRPS_FK FOREIGN KEY (HBS_RSA_PADDING_ID) REFERENCES THE.HBS_RSA_PADDING_SCHEME(HBS_RSA_PADDING_ID);

-- V1.3.2__base_table_HARVESTING_AUTHORITY.sql (Verify)
--ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_CLRC_FK FOREIGN KEY (CROWN_LANDS_REGION_CODE) REFERENCES THE.CROWN_LANDS_REGION_CODE(CROWN_LANDS_REGION_CODE);
--ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_CSC_FK FOREIGN KEY (CASCADE_SPLIT_CODE) REFERENCES THE.CASCADE_SPLIT_CODE(CASCADE_SPLIT_CODE);
ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_GEO_OU_FK FOREIGN KEY (GEOGRAPHIC_DISTRICT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
--ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_HAERC_FK FOREIGN KEY (HARVEST_AUTH_EXTEND_REAS_CODE) REFERENCES THE.HARVEST_AUTH_EXTEND_REAS_CODE(HARVEST_AUTH_EXTEND_REAS_CODE);
--ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_HASC_FK FOREIGN KEY (HARVEST_AUTH_STATUS_CODE) REFERENCES THE.HARVEST_AUTH_STATUS_CODE(HARVEST_AUTH_STATUS_CODE);
--ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_HTC_FK FOREIGN KEY (HARVEST_TYPE_CODE) REFERENCES THE.HARVEST_TYPE_CODE(HARVEST_TYPE_CODE);
--ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_LTCCD_FK FOREIGN KEY (LICENCE_TO_CUT_CODE) REFERENCES THE.LICENCE_TO_CUT_CODE(LICENCE_TO_CUT_CODE);
--ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_MUTC_FK FOREIGN KEY (MGMT_UNIT_TYPE_CODE) REFERENCES THE.MGMT_UNIT_TYPE_CODE(MGMT_UNIT_TYPE_CODE);
ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_OU_FK FOREIGN KEY (FOREST_DISTRICT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_PFU_FK FOREIGN KEY (FOREST_FILE_ID) REFERENCES THE.PROV_FOREST_USE(FOREST_FILE_ID);
--ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_QTC_FK FOREIGN KEY (QUOTA_TYPE_CODE) REFERENCES THE.QUOTA_TYPE_CODE(QUOTA_TYPE_CODE);
--ALTER TABLE THE.HARVESTING_AUTHORITY ADD CONSTRAINT HVA_SALVTCD_FK FOREIGN KEY (SALVAGE_TYPE_CODE) REFERENCES THE.SALVAGE_TYPE_CODE(SALVAGE_TYPE_CODE);

-- V1.3.0__base_table_CUT_BLOCK_OPEN_ADMIN.sql (Verify)
ALTER TABLE THE.CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT CBOA_CB_FK FOREIGN KEY (CB_SKEY) REFERENCES THE.CUT_BLOCK(CB_SKEY);
ALTER TABLE THE.CUT_BLOCK_OPEN_ADMIN ADD CONSTRAINT CBOA_O_FK FOREIGN KEY (OPENING_ID) REFERENCES THE.OPENING(OPENING_ID);

-- V1.1.17__base_table_WASTE_STRATUM_HISTORY.sql
ALTER TABLE WASTE_STRATUM_HISTORY ADD CONSTRAINT WSTRAH_WAAH_FK FOREIGN KEY (WASTE_HISTORY_ID) REFERENCES WASTE_HISTORY (WASTE_HISTORY_ID);

-- V1.1.16__base_table_WASTE_SPONSOR.sql
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT WS_WAA_FK FOREIGN KEY (WASTE_ASSESSMENT_AREA_ID) REFERENCES WASTE_ASSESSMENT_AREA (WASTE_ASSESSMENT_AREA_ID);
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT WS_WSRTC_FK FOREIGN KEY (WASTE_SUBMITTER_ROLE_TYPE_CODE) REFERENCES WASTE_SUBMITTER_ROLE_TYPE_CODE (WASTE_SUBMITTER_ROLE_TYPE_CODE);
ALTER TABLE WASTE_SPONSOR ADD CONSTRAINT WS_WDTC1_FK FOREIGN KEY (WASTE_DESIGNATION_TYPE_CODE) REFERENCES WASTE_DESIGNATION_TYPE_CODE (WASTE_DESIGNATION_TYPE_CODE);

-- V1.1.13__base_table_WASTE_PLOT_HISTORY.sql
ALTER TABLE WASTE_PLOT_HISTORY ADD CONSTRAINT WPLOH_WSTRAH_FK FOREIGN KEY (WASTE_HISTORY_ID, WASTE_STRATUM_ID) REFERENCES WASTE_STRATUM_HISTORY (WASTE_HISTORY_ID, WASTE_STRATUM_ID);

-- V1.1.12__base_table_WASTE_PIECE.sql (Verify)
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_BC_FK FOREIGN KEY (WASTE_BORDERLINE_CODE) REFERENCES THE.WASTE_BORDERLINE_CODE(WASTE_BORDERLINE_CODE);
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_DTC_FK FOREIGN KEY (WASTE_DECAY_TYPE_CODE) REFERENCES THE.WASTE_DECAY_TYPE_CODE(WASTE_DECAY_TYPE_CODE);
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_PEC_BUTT_FK FOREIGN KEY (BUTT_END_CODE) REFERENCES THE.WASTE_PIECE_END_CODE(WASTE_PIECE_END_CODE);
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_PEC_TOP_FK FOREIGN KEY (TOP_END_CODE) REFERENCES THE.WASTE_PIECE_END_CODE(WASTE_PIECE_END_CODE);
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_SPGX_FK FOREIGN KEY (SCALE_SPECIES_CODE,SCALE_PRODUCT_CODE,SCALE_GRADE_CODE) REFERENCES THE.SPECIES_PRODUCT_GRADE_XREF(SCALE_SPECIES_CODE,SCALE_PRODUCT_CODE,SCALE_GRADE_CODE);
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_WACC_FK FOREIGN KEY (WASTE_COMMENT_CODE) REFERENCES THE.WASTE_COMMENT_CODE(WASTE_COMMENT_CODE);
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_WCC_FK FOREIGN KEY (WASTE_CLASS_CODE) REFERENCES THE.WASTE_CLASS_CODE(WASTE_CLASS_CODE);
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_WMKC_FK FOREIGN KEY (WASTE_MATERIAL_KIND_CODE) REFERENCES THE.WASTE_MATERIAL_KIND_CODE(WASTE_MATERIAL_KIND_CODE);
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_WPLO_FK FOREIGN KEY (WASTE_PLOT_ID) REFERENCES THE.WASTE_PLOT(WASTE_PLOT_ID);
ALTER TABLE THE.WASTE_PIECE ADD CONSTRAINT WPIE_WSTR_FK FOREIGN KEY (WASTE_STRATUM_ID) REFERENCES THE.WASTE_STRATUM(WASTE_STRATUM_ID);

-- V1.1.11__base_table_WASTE_PIECE_HISTORY.sql
ALTER TABLE WASTE_PIECE_HISTORY ADD CONSTRAINT WPIEH_WH_FK FOREIGN KEY (WASTE_HISTORY_ID) REFERENCES WASTE_HISTORY (WASTE_HISTORY_ID);

-- V1.1.8__base_table_WASTE_ASSESSMENT_AREA_HISTORY.sql
ALTER TABLE WASTE_ASSESSMENT_AREA_HISTORY ADD CONSTRAINT WAAH_WH_FK FOREIGN KEY (WASTE_HISTORY_ID) REFERENCES WASTE_HISTORY (WASTE_HISTORY_ID);

-- V1.1.5__base_table_SAMPLE_LOG_TALLY.sql (Verify)
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_BATDOC_FK FOREIGN KEY (BATDOC_ID) REFERENCES <?>();
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_DTLSCLDOC_FK FOREIGN KEY (DETAIL_DOCUMENT_NUMBER) REFERENCES <?>();
ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_HCM_FK FOREIGN KEY (HBS_CRYPT_METHOD_ID) REFERENCES THE.HBS_CRYPTOGRAPHY_METHOD(HBS_CRYPT_METHOD_ID);
ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_HEK_FK1 FOREIGN KEY (HBS_ENCR_KEY_ID) REFERENCES THE.HBS_ENCRYPTION_KEY(HBS_ENCR_KEY_ID);
ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_HRPS_FK FOREIGN KEY (HBS_RSA_PADDING_ID) REFERENCES THE.HBS_RSA_PADDING_SCHEME(HBS_RSA_PADDING_ID);
ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_MOF_HATM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.HAULING_AUTHORITY(TIMBER_MARK);
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_MOF_SS_FK FOREIGN KEY (SCALE_SITE_ID_NMBR) REFERENCES <?>();
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_MOF_TM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.TIMBER_MARK(TIMBER_MARK);
ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_ORGDDNDDV_FK FOREIGN KEY (ORIGINAL_DDN,ORIGINAL_DDV) REFERENCES THE.SAMPLE_LOG_TALLY(DETAIL_DOCUMENT_NUMBER,VERSION);
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_ORIG_CHK_SCL_SCLR_FK FOREIGN KEY (ORIG_CHK_SCL_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_PRIMARY_SCLR_FK FOREIGN KEY (PRIMARY_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_SECONDARY_SCLR_FK FOREIGN KEY (SECONDARY_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_SETC_FK FOREIGN KEY (SCALE_EVENT_TYPE_CODE) REFERENCES <?>();
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_SIGNING_SCLR_FK FOREIGN KEY (SIGNING_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_SRVERSTATE_FK FOREIGN KEY (SCL_RTN_VERSION_STATE_CODE) REFERENCES <?>();
--ALTER TABLE THE.SAMPLE_LOG_TALLY ADD CONSTRAINT SMPLOGTLY_STRATUM_FK FOREIGN KEY (POPULATION_NUMBER,STRATUM_NUMBER,SAMPLING_YEAR) REFERENCES <?>();

-- V1.1.4__base_table_HBS_SCALER_AUTH_KEY.sql (Verify)
--ALTER TABLE THE.HBS_SCALER_AUTH_KEY ADD CONSTRAINT HBS_SAK_SCALER FOREIGN KEY (CLIENT_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.HBS_SCALER_AUTH_KEY ADD CONSTRAINT SAKEHT_HBS_HU_FK FOREIGN KEY (USER_ID) REFERENCES <?>();

-- V1.1.2__base_table_HBS_ENCRYPTION_KEY.sql
ALTER TABLE HBS_ENCRYPTION_KEY ADD CONSTRAINT HEK_HCM_FK FOREIGN KEY (HBS_CRYPT_METHOD_ID) REFERENCES HBS_CRYPTOGRAPHY_METHOD (HBS_CRYPT_METHOD_ID);

-- V1.1.6__base_table_SPECIES_PRODUCT_GRADE_XREF.sql
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SSPGXREF_HBS_SGC_FK FOREIGN KEY (SCALE_GRADE_CODE) REFERENCES SCALE_GRADE_CODE (SCALE_GRADE_CODE);
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SSPGXREF_HBS_SSC_FK FOREIGN KEY (SCALE_SPECIES_CODE) REFERENCES SCALE_SPECIES_CODE (SCALE_SPECIES_CODE);
ALTER TABLE SPECIES_PRODUCT_GRADE_XREF ADD CONSTRAINT SSPGXREF_HBS_SPC_FK FOREIGN KEY (SCALE_PRODUCT_CODE) REFERENCES SCALE_PRODUCT_CODE (SCALE_PRODUCT_CODE);

-- V1.1.14__base_table_WASTE_REPORTING_UNIT.sql (Verify)
--ALTER TABLE THE.WASTE_REPORTING_UNIT ADD CONSTRAINT WRU_AMC_FK FOREIGN KEY (APPRAISAL_METHOD_CODE) REFERENCES <?>();
ALTER TABLE THE.WASTE_REPORTING_UNIT ADD CONSTRAINT WRU_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.WASTE_REPORTING_UNIT ADD CONSTRAINT WRU_OU_FK FOREIGN KEY (ORG_UNIT_NO) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.WASTE_REPORTING_UNIT ADD CONSTRAINT WRU_SOC_FK FOREIGN KEY (WASTE_SAMPLING_OPTION_CODE) REFERENCES THE.WASTE_SAMPLING_OPTION_CODE(WASTE_SAMPLING_OPTION_CODE);
ALTER TABLE THE.WASTE_REPORTING_UNIT ADD CONSTRAINT WRU_WACV_FK FOREIGN KEY (WASTE_ACCUMULATED_CV_CODE) REFERENCES THE.WASTE_ACCUMULATED_CV_CODE(WASTE_ACCUMULATED_CV_CODE);
ALTER TABLE THE.WASTE_REPORTING_UNIT ADD CONSTRAINT WRU_WDCV_FK FOREIGN KEY (WASTE_DISPERSED_CV_CODE) REFERENCES THE.WASTE_DISPERSED_CV_CODE(WASTE_DISPERSED_CV_CODE);

-- V1.1.15__base_table_WASTE_RESIDUE_RATE.sql (Verify)
ALTER TABLE THE.WASTE_RESIDUE_RATE ADD CONSTRAINT WRR_HAA_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.HAULING_AUTHORITY(TIMBER_MARK);
ALTER TABLE THE.WASTE_RESIDUE_RATE ADD CONSTRAINT WRR_WRSC_FK FOREIGN KEY (WASTE_RATE_SOURCE_CODE) REFERENCES THE.WASTE_RATE_SOURCE_CODE(WASTE_RATE_SOURCE_CODE);
ALTER TABLE THE.WASTE_RESIDUE_RATE ADD CONSTRAINT WSTRATE_HBS_SGC_FK FOREIGN KEY (SCALE_GRADE_CODE) REFERENCES THE.SCALE_GRADE_CODE(SCALE_GRADE_CODE);
ALTER TABLE THE.WASTE_RESIDUE_RATE ADD CONSTRAINT WSTRATE_HBS_SPC_FK FOREIGN KEY (SCALE_PRODUCT_CODE) REFERENCES THE.SCALE_PRODUCT_CODE(SCALE_PRODUCT_CODE);
ALTER TABLE THE.WASTE_RESIDUE_RATE ADD CONSTRAINT WSTRATE_HBS_SSC_FK FOREIGN KEY (SCALE_SPECIES_CODE) REFERENCES THE.SCALE_SPECIES_CODE(SCALE_SPECIES_CODE);

-- V1.3.8__base_table_PIECE_SCALE_SUMMARY.sql (Verify)
--ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_HBSSR_FK FOREIGN KEY (DOCUMENT_CONTROL_NUMBER) REFERENCES <?>();
ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_MOF_CL_COPIED_TO_FK FOREIGN KEY (CLIENT_NUMBER_COPIED_TO,CLIENT_LOCN_CODE_COPIED_TO) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_MOF_CL_FK FOREIGN KEY (CLIENT_NUMBER_PAID_BY,CLIENT_LOCN_CODE_PAID_BY) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_MOF_HATM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.HAULING_AUTHORITY(TIMBER_MARK);
--ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_MOF_SCLR_FK FOREIGN KEY (LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_MOF_SS_FK FOREIGN KEY (SCALE_SITE_ID_NMBR) REFERENCES <?>();
--ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_MOF_TM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.TIMBER_MARK(TIMBER_MARK);
--ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_PSMRYTYPCD_FK FOREIGN KEY (PSSMRY_TYPE) REFERENCES <?>();
--ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_SRCATCD_FK FOREIGN KEY (SCL_RTN_CATEGORY_CODE) REFERENCES <?>();
--ALTER TABLE THE.PIECE_SCALE_SUMMARY ADD CONSTRAINT PSSMRY_SRVERSTATE_FK FOREIGN KEY (SCL_RTN_VERSION_STATE_CODE) REFERENCES <?>();

-- V1.3.9__base_table_PROV_FOREST_USE.sql (Verify)
ALTER TABLE THE.PROV_FOREST_USE ADD CONSTRAINT PFU_BCTS_OU_FK FOREIGN KEY (BCTS_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
--ALTER TABLE THE.PROV_FOREST_USE ADD CONSTRAINT PFU_FMU_FK FOREIGN KEY (MGMT_UNIT_ID,MGMT_UNIT_TYPE) REFERENCES <?>();
--ALTER TABLE THE.PROV_FOREST_USE ADD CONSTRAINT PFU_FTCD_FK FOREIGN KEY (FILE_TYPE_CODE) REFERENCES THE.FILE_TYPE_CODE(FILE_TYPE_CODE);
ALTER TABLE THE.PROV_FOREST_USE ADD CONSTRAINT PFU_OU_FK FOREIGN KEY (FOREST_REGION) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
--ALTER TABLE THE.PROV_FOREST_USE ADD CONSTRAINT PFU_TFSCD_FK FOREIGN KEY (FILE_STATUS_ST) REFERENCES THE.TENURE_FILE_STATUS_CODE(TENURE_FILE_STATUS_CODE);

-- V1.0.1__code_table_HBS_EDIT_ERR_MESSAGE_CODE.sql (Verify)
--ALTER TABLE THE.HBS_EDIT_ERR_MESSAGE_CODE ADD CONSTRAINT EEMC_ECC_FK FOREIGN KEY (HBS_EDIT_ERR_CATEGORY_CODE) REFERENCES <?>();
--ALTER TABLE THE.HBS_EDIT_ERR_MESSAGE_CODE ADD CONSTRAINT EEMC_EERESPCD_FK FOREIGN KEY (HBS_EDIT_ERR_RESPONSIBLTY_CODE) REFERENCES <?>();

-- V1.3.3__base_table_HAULING_AUTHORITY.sql (Verify)
--ALTER TABLE THE.HAULING_AUTHORITY ADD CONSTRAINT HAA_MICD_FK FOREIGN KEY (MARKING_INSTRUMENT_CODE) REFERENCES THE.MARKING_INSTRUMENT_CODE(MARKING_INSTRUMENT_CODE);
--ALTER TABLE THE.HAULING_AUTHORITY ADD CONSTRAINT HAA_MMCD_FK FOREIGN KEY (MARKING_METHOD_CODE) REFERENCES THE.MARKING_METHOD_CODE(MARKING_METHOD_CODE);
ALTER TABLE THE.HAULING_AUTHORITY ADD CONSTRAINT HAA_PFU_FK FOREIGN KEY (FOREST_FILE_ID) REFERENCES THE.PROV_FOREST_USE(FOREST_FILE_ID);

-- V1.1.0__base_table_DTL_SCL_DOC_TRANSMISSION.sql (Verify)
ALTER TABLE THE.DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT DTLDOCTRAN_MOF_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
--ALTER TABLE THE.DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT DTLDOCTRAN_PROCESSTAT_FK FOREIGN KEY (HBS_PROCESSING_STATUS_CODE) REFERENCES <?>();
--ALTER TABLE THE.DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT DTLDOCTRAN_XMLPRGSTCD_FK FOREIGN KEY (HBS_XML_PURGE_STATUS_CODE) REFERENCES <?>();
--ALTER TABLE THE.DTL_SCL_DOC_TRANSMISSION ADD CONSTRAINT DTLDOCTRAN_XMLTRNSTEP_FK FOREIGN KEY (HBS_XML_TRANS_STEP_CODE) REFERENCES <?>();

-- V1.1.9__base_table_WASTE_ASSESSMENT_SEGREGATION.sql (Verify)
ALTER TABLE THE.WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT WAS_SPGX_FK FOREIGN KEY (SCALE_SPECIES_CODE,SCALE_PRODUCT_CODE,SCALE_GRADE_CODE) REFERENCES THE.SPECIES_PRODUCT_GRADE_XREF(SCALE_SPECIES_CODE,SCALE_PRODUCT_CODE,SCALE_GRADE_CODE);
ALTER TABLE THE.WASTE_ASSESSMENT_SEGREGATION ADD CONSTRAINT WAS_WAA_FK FOREIGN KEY (WASTE_ASSESSMENT_AREA_ID) REFERENCES THE.WASTE_ASSESSMENT_AREA(WASTE_ASSESSMENT_AREA_ID);

-- V1.1.10__base_table_WASTE_HISTORY.sql
ALTER TABLE WASTE_HISTORY ADD CONSTRAINT WH_WAA_FK FOREIGN KEY (WASTE_ASSESSMENT_AREA_ID) REFERENCES WASTE_ASSESSMENT_AREA (WASTE_ASSESSMENT_AREA_ID);

-- V1.3.14__base_table_WASTE_PLOT.sql
ALTER TABLE WASTE_PLOT ADD CONSTRAINT WPLO_WSTR_FK FOREIGN KEY (WASTE_STRATUM_ID) REFERENCES WASTE_STRATUM;

-- V1.1.7__base_table_WASTE_ASSESS_AREA_STS_AUDIT.sql (Verify)
--ALTER TABLE THE.WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT WAASA_HSR_FK FOREIGN KEY (DOCUMENT_CONTROL_NUMBER) REFERENCES <?>();
ALTER TABLE THE.WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT WAASA_WAASC_FK FOREIGN KEY (WASTE_ASSESS_AREA_STS_CODE) REFERENCES THE.WASTE_ASSESS_AREA_STS_CODE(WASTE_ASSESS_AREA_STS_CODE);
ALTER TABLE THE.WASTE_ASSESS_AREA_STS_AUDIT ADD CONSTRAINT WAASA_WAA_FK FOREIGN KEY (WASTE_ASSESSMENT_AREA_ID) REFERENCES THE.WASTE_ASSESSMENT_AREA(WASTE_ASSESSMENT_AREA_ID);


-- V1.1.18__base_table_WEIGH_SLIP.sql (Verify)
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_BATDOC_FK FOREIGN KEY (BATDOC_ID) REFERENCES <?>();
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_DTLSCLDOC_FK FOREIGN KEY (DETAIL_DOCUMENT_NUMBER) REFERENCES <?>();
ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_MOF_HATM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.HAULING_AUTHORITY(TIMBER_MARK);
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_MOF_SS_FK FOREIGN KEY (SCALE_SITE_ID_NMBR) REFERENCES <?>();
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_MOF_TM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.TIMBER_MARK(TIMBER_MARK);
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_PRIMARY_SCLR_FK FOREIGN KEY (PRIMARY_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_SECONDARY_SCLR_FK FOREIGN KEY (SECONDARY_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_SETC_FK FOREIGN KEY (SCALE_EVENT_TYPE_CODE) REFERENCES <?>();
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_SIGNING_SCLR_FK FOREIGN KEY (SIGNING_LICENSE_NUMBER) REFERENCES <?>();
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_SMPLTYPECD_FK FOREIGN KEY (HBS_SAMPLE_TYPE_CODE) REFERENCES <?>();
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_STRATUM_FK FOREIGN KEY (POPULATION_NUMBER,STRATUM_NUMBER,SAMPLING_YEAR) REFERENCES <?>();
--ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WSDR_VER_STATUS_FK FOREIGN KEY (SCL_RTN_VERSION_STATE_CODE) REFERENCES <?>();
ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WST_HCM_FK FOREIGN KEY (HBS_CRYPT_METHOD_ID) REFERENCES THE.HBS_CRYPTOGRAPHY_METHOD(HBS_CRYPT_METHOD_ID);
ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WST_HEK_FK1 FOREIGN KEY (HBS_ENCR_KEY_ID) REFERENCES THE.HBS_ENCRYPTION_KEY(HBS_ENCR_KEY_ID);
ALTER TABLE THE.WEIGH_SLIP ADD CONSTRAINT WST_HRPS_FK FOREIGN KEY (HBS_RSA_PADDING_ID) REFERENCES THE.HBS_RSA_PADDING_SCHEME(HBS_RSA_PADDING_ID);

-- V1.3.13__base_table_WASTE_BILLING_XREF.sql
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT WBX_WMCC_FK FOREIGN KEY (WASTE_MATERIAL_CLASS_CODE) REFERENCES WASTE_MATERIAL_CLASS_CODE(WASTE_MATERIAL_CLASS_CODE);
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT WBX_SGC_FK FOREIGN KEY (SCALE_GRADE_CODE) REFERENCES SCALE_GRADE_CODE(SCALE_GRADE_CODE);
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT WBX_WCC_FK FOREIGN KEY (WASTE_CLASS_CODE) REFERENCES WASTE_CLASS_CODE(WASTE_CLASS_CODE);
ALTER TABLE WASTE_BILLING_XREF ADD CONSTRAINT WBX_WMKC_FK FOREIGN KEY (WASTE_MATERIAL_KIND_CODE) REFERENCES WASTE_MATERIAL_KIND_CODE(WASTE_MATERIAL_KIND_CODE);

-- V1.3.6__base_table_OPENING.sql
ALTER TABLE OPENING ADD CONSTRAINT O_OU_FK FOREIGN KEY (ADMIN_DISTRICT_NO) REFERENCES ORG_UNIT;
ALTER TABLE OPENING ADD CONSTRAINT O_OU_RESIDES_WITHIN_FK FOREIGN KEY (GEO_DISTRICT_NO) REFERENCES ORG_UNIT;
--ALTER TABLE OPENING ADD CONSTRAINT O_SAZ_FK FOREIGN KEY (ORG_UNIT_NO, DIST_ADMIN_ZONE) REFERENCES ORG_UNIT;
--ALTER TABLE OPENING ADD CONSTRAINT O_TSC2_FK FOREIGN KEY (PREV_TREE_SPP2_CODE) REFERENCES TREE_SPECIES_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_OCC_FK FOREIGN KEY (OPEN_CATEGORY_CODE) REFERENCES OPEN_CATEGORY_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_SSC6_FK FOREIGN KEY (PREV_STOCKING_STATUS_CODE) REFERENCES STOCKING_STATUS_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_ACC_FK FOREIGN KEY (PREV_AGE_CLASS_CODE) REFERENCES AGE_CLASS_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_HCC_FK FOREIGN KEY (PREV_HEIGHT_CLASS_CODE) REFERENCES HEIGHT_CLASS_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_OSC_FK FOREIGN KEY (OPENING_STATUS_CODE) REFERENCES OPENING_STATUS_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_RES_FK FOREIGN KEY (RESULTS_SUBMISSION_ID) REFERENCES RESULTS_SUBMISSION;
--ALTER TABLE OPENING ADD CONSTRAINT O_SCC1_FK FOREIGN KEY (PREV_STOCKING_CLASS_CODE) REFERENCES STOCKING_CLASS_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_SCC2_FK FOREIGN KEY (PREV_SITE_CLASS_CODE) REFERENCES SITE_CLASS_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_SISC_FK FOREIGN KEY (PREV_SITE_INDEX_SOURCE_CODE) REFERENCES SITE_INDEX_SOURCE_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_TNC1_FK FOREIGN KEY (TSB_NUMBER_CODE) REFERENCES TSB_NUMBER_CODE;
--ALTER TABLE OPENING ADD CONSTRAINT O_TSC1_FK FOREIGN KEY (PREV_TREE_SPP1_CODE) REFERENCES TREE_SPECIES_CODE;

-- V1.3.1__base_table_CUT_BLOCK.sql
--ALTER TABLE CUT_BLOCK ADD CONSTRAINT CBLK_FHRC_FK FOREIGN KEY (FIRE_HARVESTING_REASON_CODE) REFERENCES FIRE_HARVESTING_REASON_CODE;
ALTER TABLE CUT_BLOCK ADD CONSTRAINT CB_HVA_FK FOREIGN KEY (HVA_SKEY) REFERENCES HARVESTING_AUTHORITY;
--ALTER TABLE CUT_BLOCK ADD CONSTRAINT CB_CRC_FK FOREIGN KEY (CUT_REGULATION_CODE) REFERENCES CUT_REGULATION_CODE;
--ALTER TABLE CUT_BLOCK ADD CONSTRAINT CBLK_BSCD_FK FOREIGN KEY (BLOCK_STATUS_ST) REFERENCES BLOCK_STATUS_CODE;
--ALTER TABLE CUT_BLOCK ADD CONSTRAINT CBLK_TM_FK FOREIGN KEY (TIMBER_MARK) REFERENCES TIMBER_MARK;
ALTER TABLE CUT_BLOCK ADD CONSTRAINT CB_HAA_FK FOREIGN KEY (TIMBER_MARK) REFERENCES HAULING_AUTHORITY(TIMBER_MARK);
--ALTER TABLE CUT_BLOCK ADD CONSTRAINT CB_RDTC_FK FOREIGN KEY (REPORTED_FIRE_DATE) REFERENCES REPORTED_FIRE_DATE;
--ALTER TABLE CUT_BLOCK ADD CONSTRAINT CB_RDTC_FK FOREIGN KEY (REFOREST_DECLARE_TYPE_CODE) REFERENCES REFOREST_DECLARE_TYPE_CODE(REFOREST_DECLARE_TYPE_CODE);


ALTER TABLE THE.HARVESTING_HAULING_XREF ADD CONSTRAINT HHX_HAA_FK FOREIGN KEY (TIMBER_MARK) REFERENCES THE.HAULING_AUTHORITY(TIMBER_MARK);
ALTER TABLE THE.HARVESTING_HAULING_XREF ADD CONSTRAINT HHX_HVA_FK FOREIGN KEY (HVA_SKEY) REFERENCES THE.HARVESTING_AUTHORITY(HVA_SKEY);
