-- Data pump for WASTE_TYPE_STRATUM_XREF
INSERT INTO WASTE_TYPE_STRATUM_XREF (WASTE_TYPE_CODE, WASTE_STRATUM_TYPE_CODE)
VALUES
('C','ACC'),
('D','DIS'),
('F','DIS'),
('G','DIS'),
('H','DIS'),
('L','ACC'),
('O','ACC'),
('P','ACC'),
('R','ACC'),
('S','DIS');
INSERT INTO WASTE_TYPE_STRATUM_XREF (WASTE_TYPE_CODE, WASTE_STRATUM_TYPE_CODE)
VALUES
('T','DIS'),
('W','ACC');
