apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: nr-waste-plus
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: DB_PASSWORD
    description: Password for the PostgreSQL connection user.
    required: true
  - name: ORACLEDB_USER
    description: Oracle database user name
    required: true
  - name: ORACLEDB_PASSWORD
    description: Oracle database password
    required: true    
  - name: ORACLEDB_DATABASE
    description: Oracle database database name
    required: true
  - name: ORACLEDB_HOST
    description: Oracle database host
    required: true
  - name: ORACLEDB_SERVICENAME
    description: Oracle database service name
    required: true
  - name: ORACLEDB_SECRET
    description: Oracle database keystore secret/password
    required: true
  - name: IDX_PVC_SIZE
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Database Volume Capacity
    required: true
    value: 256Mi
  - name: COGNITO_CLIENT_ID
    required: true
  - name: COGNITO_DOMAIN
    value: 'prod-fam-user-pool-domain'
  - name: COGNITO_ENVIRONMENT
    required: true
  - name: COGNITO_USER_POOL
    description: Cognito user pool id
    required: true
  - name: COGNITO_REGION
    description: Cognito region information
    value: 'ca-central-1'
  - name: VITE_LEGACY_BASE_URL
    description: Green domain
    required: true
  - name: LANDING_URL
    required: true
  - name: URL_FRONTEND
    description: Frontend URL
    required: true
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: SPRING_PROFILES_ACTIVE
    description: Spring profile
    required: true
  - name: VITE_NODE_ENV
    required: true
  - name: VITE_CLIENT_BASE_URL
    required: true
  - name: CLIENT_BASE_URL
    required: true
  - name: CLIENT_BASE_KEY
    required: true
  - name: VITE_ZONE
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-name: ${NAME}
      database-password: ${DB_PASSWORD}
      database-user: ${NAME}  
      oracle-user: ${ORACLEDB_USER}
      oracle-password: ${ORACLEDB_PASSWORD}
      oracle-database: ${ORACLEDB_DATABASE}
      oracle-host: ${ORACLEDB_HOST}
      oracle-service: ${ORACLEDB_SERVICENAME}
      oracle-secret: ${ORACLEDB_SECRET}  
      cognito-user-pool: ${COGNITO_USER_POOL}
      cognito-environment: ${COGNITO_ENVIRONMENT}      
      spring-profiles-active: "container,${SPRING_PROFILES_ACTIVE}"
      client-base-url: ${CLIENT_BASE_URL}
      client-base-key: ${CLIENT_BASE_KEY}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: quickstart-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-frontend
    data:
      config.js: |
        window.config.setItem('VITE_BACKEND_URL', 'https://${NAME}-${ZONE}-backend.${DOMAIN}');
        window.config.setItem('VITE_FRONTEND_URL', 'https://${URL_FRONTEND}');
        window.config.setItem('VITE_NODE_ENV', '${VITE_NODE_ENV}');
        window.config.setItem('VITE_APP_NAME', 'Waste Plus');
        window.config.setItem('VITE_FEATURES_OFFLINE', 'true');
        window.config.setItem('VITE_ZONE', '${VITE_ZONE}');
        window.config.setItem('VITE_USER_POOLS_ID', '${COGNITO_USER_POOL}');
        window.config.setItem('VITE_LEGACY_BASE_URL', '${VITE_LEGACY_BASE_URL}');
        window.config.setItem('VITE_CLIENT_BASE_URL', '${CLIENT_BASE_URL}');
        window.config.setItem('VITE_USER_POOLS_WEB_CLIENT_ID', '${COGNITO_CLIENT_ID}');
