name: Automated user flow tests

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  cypress-run:
    name: "User flow test"
    permissions:
      pull-requests: write
    runs-on: ubuntu-24.04
    environment: tools
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        name: Start node
        with:
          node-version: 24

      - name: Run Cypress End-to-End
        uses: cypress-io/github-action@v7.1.10
        with:
          working-directory: cypress
          browser: chrome
          install-command: npm ci
        env:
          CYPRESS_baseUrl: https://${{ inputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
          CYPRESS_idir_password: ${{ secrets.IDIR_UAT_PASSWORD }}
          CYPRESS_idir_username: ${{ secrets.IDIR_UAT_USERNAME }}
          MOCHAWESOME_REPORT: true
          CYPRESS_MOCHAWESOME_REPORT: true
          CYPRESS_bceid_password: ${{ secrets.BCEID_UAT_PASSWORD }}
          CYPRESS_bceid_username: ${{ secrets.BCEID_UAT_USERNAME }}
