name: Route TLS

on:
  workflow_dispatch:

permissions: {}

jobs:
  route-tls:
    name: Route TLS (PROD)
    environment: prod
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: bcgov/actions-openshift/route-tls@75454b2b33edf37135f6f167775c77a3414207f6 # v0.3.1
        with:
          hostname: wasteplus.nrs.gov.bc.ca
          target_service: nr-waste-plus-prod-frontend
          tls_certificate: ${{ secrets.TLS_CERTIFICATE }}
          tls_private_key: ${{ secrets.TLS_PRIVATE_KEY }}
          tls_ca_certificate: ${{ secrets.TLS_CA_CERTIFICATE }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          dry_run: "true"
